### ISSUE TITLE
多个公众号下载

### ISSUE THREAD

**Issue by LiuDuFenLi** [qiye45/wechatDownload#101]
1.多个公众号文章下载，建议把“微信文章链接” input 修改成textarea，多篇文章以符号隔开，程序按照队列处理。
本人在使用剪切板功能时软件频繁崩溃。
2.建议不使用固定等待时间。

**Comment by qiye45** [comment]
现在不是等待时间啦，会加上随机等待时间哒

**Comment by qiye45** [comment]
2.5支持多个公众号文章下载啦，剪切板应该稳定一点了

**Comment by qiye45** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/138199658/605e9c7b-7748-4699-9db8-4f7ae05b5583)
