### ISSUE TITLE
下载全部公众号文章，提示获取秘钥，然后自动退出程序【闪退】

### ISSUE THREAD

**Issue by fqh1995** [qiye45/wechatDownload#105]
描述该错误
对该错误的简明扼要的描述。
下载较慢
截图
添加截图以帮助解释你的问题。

其他信息
在这里添加关于该问题的任何其他背景。
2.4版本

**Comment by qiye45** [comment]
用新版本...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月21日(周二) 中午12:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 下载全部公众号文章，提示获取秘钥，然后自动退出程序【闪退】 (Issue #105)




 
描述该错误
 对该错误的简明扼要的描述。
 下载较慢
 截图
 添加截图以帮助解释你的问题。
 
其他信息
 在这里添加关于该问题的任何其他背景。
 2.4版本

**Comment by fqh1995** [comment]
好的，正在使用，感谢答疑

**Comment by superman103** [comment]
2.5版本总是下载几篇文章就闪退是什么情况啊，win10系统64位

**Comment by qiye45** [comment]
试试新上传这个
![image](https://github.com/qiye45/wechatDownload/assets/138199658/bc4f74aa-e840-40f7-af7c-063f0a4751f3)

**Comment by MazzaWill** [comment]
2.6版本依旧闪退
