### ISSUE TITLE
为什么导出表格，导着导着就卡住不动的呢

### ISSUE THREAD

**Issue by ouyanglxy** [qiye45/wechatDownload#106]
![image](https://github.com/qiye45/wechatDownload/assets/155046535/cb109120-c1c9-429f-bcf5-aa23c8f5bbb3)

**Comment by qiye45** [comment]
截全一点，带上链接...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月21日(周二) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 为什么导出表格，导着导着就卡住不动的呢 (Issue #106)




 
image.png (view on web)

**Comment by ouyanglxy** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/155046535/39e2d531-9269-49d2-ac99-1afb10304f50)
