### ISSUE TITLE
macos下载后无法使用，提示不支持

### ISSUE THREAD

**Issue by AmazingRobin** [qiye45/wechatDownload#107]
系统版本
<img width="255" alt="截屏2024-05-24 23 16 28" src="https://github.com/qiye45/wechatDownload/assets/3375892/c0b4fa93-ff83-4dfb-882a-121c10c6a907">

<img width="207" alt="截屏2024-05-24 23 17 57" src="https://github.com/qiye45/wechatDownload/assets/3375892/3b1b5abe-9a91-4f03-a13b-0f5ada2ebe47">
 ---------------------- ---------------------- ----------------------这样 ----------------------
<img width="259" alt="截屏2024-05-24 23 18 02" src="https://github.com/qiye45/wechatDownload/assets/3375892/6d71ddcd-f8d2-4b65-a551-ff367e651849">

**Comment by qiye45** [comment]
可能要苹果芯片的

**Comment by qiye45** [comment]
环境
![image](https://github.com/qiye45/wechatDownload/assets/138199658/5853eb01-8b29-450d-81d7-6b780b9ef902)
![image](https://github.com/qiye45/wechatDownload/assets/138199658/6aa30d7c-6de8-4ad8-b854-f871065abb12)

**Comment by AmazingRobin** [comment]
2.6 GHz 四核Intel Core i7

**Comment by AmazingRobin** [comment]
2.6 GHz 四核Intel Core i7
尴尬了， 可以做兼容吗

**Comment by valens7** [comment]
<img width="244" alt="image" src="https://github.com/qiye45/wechatDownload/assets/35646496/4836861e-9740-4b86-be7d-c98d6d597e24">
一样的wen't问题...

**Comment by AmazingRobin** [comment]
> <img alt="image" width="244" src="https://private-user-images.githubusercontent.com/35646496/333802178-4836861e-9740-4b86-be7d-c98d6d597e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDMxOTIsIm5iZiI6MTcxNjY0Mjg5MiwicGF0aCI6Ii8zNTY0NjQ5Ni8zMzM4MDIxNzgtNDgzNjg2MWUtOTc0MC00Yjg2LWJlN2QtYzk4ZDZkNTk3ZTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNTg2ZjhjYWExOTJhNjVmNzY3NDNlZmUyMzE3ZWQ3MDkxYmIyMmM5ZmUzYzMzYTk4YmFiYTQ4ZGU5ZmZjMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVxRM6GN3m8dG4Oi0GJ5m-J7ifUyuCM8ZvukSPf1UJM"> 一样的wen't问题...

你也是Intel芯片的吗

**Comment by qiye45** [comment]
兼容可能比较难，还得找个Intel的电脑😶‍🌫️

**Comment by AmazingRobin** [comment]
好尴尬，现在在parallels desktop虚拟机里也无法打开。。。

**Comment by qiye45** [comment]
试试开个window的虚拟机咯

**Comment by AmazingRobin** [comment]
这两天虚拟机里用的2个win7系统都不行，今天装了win10可以打开使用了。然后发现一个小问题，就是下载的时候，如果不选择《导出HTML》只选择doc或者pdf的话， 是无法下载文件的。

**Comment by sjq597** [comment]
> 环境 ![image](https://private-user-images.githubusercontent.com/138199658/332256025-5853eb01-8b29-450d-81d7-6b780b9ef902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTYyNDksIm5iZiI6MTcxODI1NTk0OSwicGF0aCI6Ii8xMzgxOTk2NTgvMzMyMjU2MDI1LTU4NTNlYjAxLThiMjktNDUwZC04MWQ3LTZiNzgwYjllZjkwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNTE5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2YxNTRjZDAxYWE0M2QyMTJjNjU0MDc4NTE3OGMyMzZiNGU1ZmNkZTVjMmI5ZGY4NGE5YzYzYzM3YThkZTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.79J2S-Da-TvCr4F4rK-vgk-WfJPigyMCFqf9Qf2KDwM) ![image](https://private-user-images.githubusercontent.com/138199658/332256047-6aa30d7c-6de8-4ad8-b854-f871065abb12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTYyNDksIm5iZiI6MTcxODI1NTk0OSwicGF0aCI6Ii8xMzgxOTk2NTgvMzMyMjU2MDQ3LTZhYTMwZDdjLTZkZTgtNGFkOC1iODU0LWY4NzEwNjVhYmIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNTE5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDk0NzA1NTg4YzQwNzg0Mjg4N2M1YWU4ZTdkZTFiYzg0YTMzNDc1OTEyMmM3YThkNDAwOTk1MWViNDc5NmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.htU_-neY8_SD-N_mtXKDJTnGNESJSXGjCIWYmEQhGo8)

M2 pro的也不行，提示文件损坏，这个是啥问题啊
<img width="532" alt="image" src="https://github.com/qiye45/wechatDownload/assets/4928331/2fbbcdea-7ad6-4cfe-9b8b-baa28f00d34c">

**Comment by haodaohong** [comment]
程序拉到 application 中后，终端里执行这段代码即可：xattr -c /Applications/wechatdownload.app

**Comment by qianxun321** [comment]
> 程序拉到 application 中后，终端里执行这段代码即可：xattr -c /Applications/wechatdownload.app

有用的

**Comment by cooker** [comment]
<img width="215" alt="企业微信20240701-121158@2x" src="https://github.com/qiye45/wechatDownload/assets/10859254/f20a8578-ac3b-419f-b649-e47d2890b483">

打不开

**Comment by nevertoday** [comment]
请问 现在支持macos了么？

**Comment by qiye45** [comment]
用网页版吧，功能差不多的 https://changfengbox.top/wechat

**Comment by wyleus** [comment]
> 程序拉到 application 中后，终端里执行这段代码即可：xattr -c /Applications/wechatdownload.app

有用的，要把程序先放到应用程序中。再执行代码

**Comment by hpan** [comment]
v2.6 后就不再发布 Mac 版了？
