### ISSUE TITLE
批量下载文章功能只下载一部分后，程序就不动，停止下载了

### ISSUE THREAD

**Issue by binjar** [qiye45/wechatDownload#108]
描述该错误
按照操作流程正常操作后，程序会自动进行文章下载，但是好几次都碰到，下载了几十篇后，软件就暂停不动了，继续点击“批量下载文章”也没有反应。

其他信息
![image](https://github.com/qiye45/wechatDownload/assets/81861926/440826bc-5a08-4a82-8fdc-b6ea155eb321)
微信版本：3.9.10.19

**Comment by qiye45** [comment]
试试新版本

**Comment by Reg2020** [comment]
新版本，好像自定义时间下载无效。

**Comment by qiye45** [comment]
截个图看看吧
