### ISSUE TITLE
如何关闭或结束下载

### ISSUE THREAD

**Issue by GerardDu** [qiye45/wechatDownload#11]
我点击软件右上角的关闭符号后，看到下载文件夹中的文件数量依然在增加。
我打开任务管理器，把 应用--Windows资源管理器--下载和后台进程--该软件 都结束任务后，看到下载文件夹中的文件数量依然在增加。

我想知道，如果下载了一部分文章后，我要中止任务，不再继续下载，该如何彻底结束下载呢？

**Comment by qiye45** [comment]
下个版本应该会加上

**Comment by GerardDu** [comment]
期待。
我在火绒中看到除了wechatdownload.exe运行外，还有  pdf.exe和docx.exe 在后台运行。

**Comment by qiye45** [comment]
2.2版本更新，关闭软件，会自动暂停啦
