### ISSUE TITLE
自动闪退

### ISSUE THREAD

**Issue by FeynmanHung** [qiye45/wechatDownload#110]
**描述该错误**
获取密钥正确的情况下，点击批量下载文章，但下载了二十来篇之后就自动闪退。
求大佬看下什么情况，感谢！

**截图**
![image](https://github.com/qiye45/wechatDownload/assets/27325930/5917be0e-0ac2-4222-8c9a-978664651914)

**Comment by qiye45** [comment]
试试旧版本咯，重新下载一下

**Comment by FeynmanHung** [comment]
2.3试了，打印出来是文章卸载失败
2.4试了，评论无法下载
但闪退的问题还是依旧存在

**Comment by qiye45** [comment]
发一下链接

**Comment by qiye45** [comment]
试试新版本

**Comment by FeynmanHung** [comment]
https://mp.weixin.qq.com/s/k0vpsH-AOLyLCEmfdOmKDg
新版本2.6依旧不行
微信版本：3.9.10.27

**Comment by FeynmanHung** [comment]
https://mp.weixin.qq.com/s/k0vpsH-AOLyLCEmfdOmKDg
新版本2.6依旧不行
微信版本：3.9.10.27
