### ISSUE TITLE
html格式打开后，内容部分白茫茫一片

### ISSUE THREAD

**Issue by iceblue0227** [qiye45/wechatDownload#111]
![image](https://github.com/qiye45/wechatDownload/assets/76610765/af79cb9d-0263-45f3-86a3-06838257f0ca)

这两日下载的HTML格式，浏览器打开后白茫茫一片。（谷歌，360，edge，viva都是白茫茫一片）

**Comment by iceblue0227** [comment]
md和word格式没有影响，就是word排版，没有md好。md里的图片用的是图床，word直接是图片

**Comment by qiye45** [comment]
发一下链接

**Comment by Ivanwu719** [comment]
我的也是，具体日期是5月27日，从28日之后，下载公众号的文章内容html格式为空白

**Comment by Ivanwu719** [comment]
例如链接：https://mp.weixin.qq.com/s/UJNkTVoW3QW9ohu4bPdy7A

**Comment by AU-Linsanity** [comment]
是的，我也是

**Comment by iceblue0227** [comment]
沉下去，走出去，遍地是黄金｜5万字解读2024餐饮
https://mp.weixin.qq.com/s/AbX-XqavQI0zMj-fArVFwg

**Comment by qiye45** [comment]
大概微信改了什么

**Comment by qiye45** [comment]
2.6新版本修复啦
![image](https://github.com/qiye45/wechatDownload/assets/138199658/1d35cc6a-9494-4f43-b99a-b2a5dec395cd)

**Comment by qiye45** [comment]
2.6更新啦

**Comment by Ivanwu719** [comment]
太感谢了，这个工具帮助我收集一些资料很有用，请你喝杯奶茶，已打赏。

**Comment by getg8642** [comment]
下载后的文章格式不能和联网打开的格式一致，尤其是表格，表格基本就没有了 
![原文章内容](https://github.com/qiye45/wechatDownload/assets/10877942/0c189bb5-2729-49db-8d4a-115a3358f7ad)
![下载后文章内容](https://github.com/qiye45/wechatDownload/assets/10877942/acb2bcd4-b3db-44a4-be71-58e98017532b)

**Comment by truebaby365** [comment]
2.7版本，怎么下载的word文档，图片都是空白呢？https://mp.weixin.qq.com/s/UhT3sdCS3bMlJb2510JHgQ 这个文章。谢谢

**Comment by qiye45** [comment]
可能网络问题，我这边正常
[间架结构92法田字格完整版.docx](https://github.com/user-attachments/files/15985027/92.docx)
![image](https://github.com/qiye45/wechatDownload/assets/138199658/c5a7593c-cc98-47c2-9944-294e5bb5481d)

**Comment by wokeryi** [comment]
为什么一直获取秘钥失败...请先在微信打开复制的链接？
