### ISSUE TITLE
没法获取公众号ID，按钮是灰色的。mac系统2.6版本

### ISSUE THREAD

**Issue by asd229000509** [qiye45/wechatDownload#113]
描述该错误
获取公众号ID，按钮一直都是灰色

截图
![Uploading image.png…]()

其他信息
复制了其他连接都一样

**Comment by qiye45** [comment]
因为还没适配，可以先试试复制链接下载咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月3日(周一) 下午2:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 没法获取公众号ID，按钮是灰色的。mac系统2.6版本 (Issue #113)




 
描述该错误
 获取公众号ID，按钮一直都是灰色
 
截图
 
 
其他信息
 复制了其他连接都一样

**Comment by zhaozhiming** [comment]
一样问题

**Comment by qiye45** [comment]
先试试复制链接下载咯，支持多个链接下载哒
