### ISSUE TITLE
显示下载成功，但在日志中仍显示下载评论失败，已关闭网络代理仍出现下载评论失败

### ISSUE THREAD

**Issue by mabwm1** [qiye45/wechatDownload#115]
版本:2.6
1.获取密钥成功，并且能够正常下载HTML，导出Word都没什么问题，下载评论一直失败。无法获取
2.下载评论回复的按钮点击不了

截图
![image](https://github.com/qiye45/wechatDownload/assets/67527532/8f436316-b75e-461c-834c-4edf1960b54f)

其他信息
我使用了之前的版本如2.3、2.4仍是这样的情况，目前只需要下载评论和回复，但是失败有解决办法吗

**Comment by qiye45** [comment]
用批量下载的

**Comment by qiye45** [comment]
或者先点获取公众号id、秘钥，获取秘钥成功后，再点文章下载
