### ISSUE TITLE
导出公众号数据的表格是乱码，而且是分开的。

### ISSUE THREAD

**Issue by kozexn** [qiye45/wechatDownload#116]
你好，开发者
导出公众号的标题、阅读数时，excel表格会出现乱码的情况，而且是一次性导出了很多个表格。下个版本可以修复吗？谢谢

![4a542f9c747e3c1417d042c879ddd6f](https://github.com/qiye45/wechatDownload/assets/110313976/8d4153ea-c13d-4ec6-92a7-e97c2321e5bc)

![a05c8052b2dd1762d57bfcbfe7efdb0](https://github.com/qiye45/wechatDownload/assets/110313976/2adcb537-4191-4826-bdcf-599756446ef5)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/38

**Comment by qiye45** [comment]
因为新版本加上了实时导出的，吧旧的删掉咯

**Comment by kozexn** [comment]
> 因为新版本加上了实时纳税，吧旧的删掉咯

赞赞赞，成功了。是excel编码问题。谢谢，谢谢巨佬！！！！
