### ISSUE TITLE
勾选默认项调整；批量下载增加暂停/取消按钮；备份正文增加原文链接；

### ISSUE THREAD

**Issue by CrossWow** [qiye45/wechatDownload#119]
**描述你想要的功能**
1、下载设置栏，勾选默认项调整；
![Snipaste_2024-06-05_15-06-55](https://github.com/qiye45/wechatDownload/assets/158282208/1f07c33a-4039-44d7-bd16-94ba3396848e)

2、批量下载增加暂停/取消按钮；
3、备份正文增加原文链接；

**Comment by qiye45** [comment]
我在md格式后面加上原文链接咯，下个版本我加上保存选项的

**Comment by CrossWow** [comment]
> 我在md格式后面加上原文链接咯，下个版本我加上保存选项的

HTML格式增加原文链接能不能实现？！

**Comment by CrossWow** [comment]
文章标题下方;
