### ISSUE TITLE
2.6版本为什么批量下载，没有Wd和PDF格式

### ISSUE THREAD

**Issue by llywjngit** [qiye45/wechatDownload#121]
描述该错误
对该错误的简明扼要的描述。

截图
添加截图以帮助解释你的问题。

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by llywjngit** [comment]
![Uploading 20240607115140.jpg…]()

**Comment by llywjngit** [comment]
![tu](https://github.com/qiye45/wechatDownload/assets/172003492/255a02b3-9435-4d70-a49c-2764cb5fc526)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/42

**Comment by llywjngit** [comment]
> #42

谢谢大佬分享
