### ISSUE TITLE
【问题反馈】“下载评论回复”选项，无法选择

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#123]
版本：2.6
问题：“下载评论回复”选项，这个选项，选不上。
截图：如下
![image](https://github.com/qiye45/wechatDownload/assets/29511872/5df33205-a638-464e-8cf0-98f1c2669f7f)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/52

**Comment by qiye45** [comment]
我看看下个版本能不能加上吧

**Comment by qiye45** [comment]
2.7 支持下载评论回复啦
