### ISSUE TITLE
【功能追加建议】下载设置的各个选项，希望能自动保存

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#124]
版本：2.6
下载设置的各个选项，每次变动后，下次再打开软件，就都恢复成默认值了，还得重新设置。
希望这些选项能自动保存，下次打开软件时，保留上次修改后的选项。

**Comment by qiye45** [comment]
下个版本我看看吧

**Comment by qiye45** [comment]
2.7支持自动保存设置的选项啦
