### ISSUE TITLE
初次使用总结，避坑指南

### ISSUE THREAD

**Issue by zzgreg** [qiye45/wechatDownload#125]
1.不要开启代理
2.不要双开微信
3.微信不要开启青少年模式
4.不要开启杀毒软件
5.作者所谓【在微信打开复制的链接】，就是把自动复制好的链接，发到微信的文件传输助手，再点击打开
6.不懂可以看作者提示的b站教程

**Comment by qiye45** [comment]
加到置顶啦

**Comment by qianyingshuo** [comment]
”5.作者所谓【在微信打开复制的链接】，就是把自动复制好的链接，发到微信的文件传输助手，再点击打开“
这句话应该加到你的readme里面

**Comment by qiye45** [comment]
加到使用教程啦👌👻

**Comment by AIophthalmology** [comment]
单章文章能下载成功，获取公众号id链接之后，微信内打卡，还是无法获取密匙

**Comment by SantaClaraBelem** [comment]
作者你好！3.2版本在Win10的22H2環境下，我根據此教程基本順利啟用了，但是用到一半（大概采集了3個公眾號的近一季度文章后），微信客戶端的內置瀏覽器上，突然對第四個公眾號的ID驗證后鏈接不予打開，提示黑體大字“操作頻繁，稍後再試”（按記憶大概是這個），重啟過暫時也不行。請問這是微信一端觸發了限制，還是其他的問題呢？不知其他人有沒遇到過這種情形，作為小白特來請教大家。

**Comment by qiye45** [comment]
> 作者你好！3.2版本在Win10的22H2環境下，我根據此教程基本順利啟用了，但是用到一半（大概采集了3個公眾號的近一季度文章后），微信客戶端的內置瀏覽器上，突然對第四個公眾號的ID驗證后鏈接不予打開，提示黑體大字“操作頻繁，稍後再試”（按記憶大概是這個），重啟過暫時也不行。請問這是微信一端觸發了限制，還是其他的問題呢？不知其他人有沒遇到過這種情形，作為小白特來請教大家。

6.操作频繁，请稍后再试；密钥过期：下载太多触发微信风控了，等一天或者换个微信 https://github.com/qiye45/wechatDownload/issues/20
