### ISSUE TITLE
【功能建议】支持正则表达式过滤文章标题

### ISSUE THREAD

**Issue by zzgreg** [qiye45/wechatDownload#126]
描述：当只对公众号的某些文章感兴趣，比如文章标题是类似：练习【第1977期】，其余的都不需要，，或者有些广告文章标题有明显特征，需要排除，此时有正则表达式会很方便。也即是说希望增加2个功能，一个功能是标题包含什么，一个功能是标题排除什么，并且分别都支持正则表达式。

**Comment by qiye45** [comment]
可以试试先下载文章，后面再删除哟
