### ISSUE TITLE
【功能建议】批量下载文章时，希望能增加进度信息。

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#127]
如题。
希望能增加如下进度信息：
进度百分比（当前已下载文章数/总预计文章数）
例：10%（10/100）

**Comment by qiye45** [comment]
我看看能不能加上吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 晚上8:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 【功能建议】批量下载文章时，希望能增加进度信息。 (Issue #127)




 
如题。
 希望能增加如下进度信息：
 进度百分比（当前已下载文章数/总预计文章数）
 例：10%（10/100）

**Comment by qiye45** [comment]
微信好像没有总页数，试试加上日期来看进度咯
