### ISSUE TITLE
为什么总是闪退呀

### ISSUE THREAD

**Issue by cathyARTME** [qiye45/wechatDownload#128]
**描述该错误**
对该错误的简明扼要的描述。

**截图**
添加截图以帮助解释你的问题。

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by hrbagang** [comment]
我是最新的2.6版本，也是经常闪退。希望能尽快修复

**Comment by qiye45** [comment]
试试旧版本会闪退吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月12日(周三) 上午6:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 为什么总是闪退呀 (Issue #128)




 
我是最新的2.6版本，也是经常闪退。希望能尽快修复

**Comment by shaojiahao** [comment]
暂停17秒后，下载几篇文章然后会闪退，其他人有遇到过吗

**Comment by qiye45** [comment]
试试2.7新版本咯
