### ISSUE TITLE
下载文章多了就卡住了，下次又要重新下载？

### ISSUE THREAD

**Issue by seagar0908** [qiye45/wechatDownload#129]
描述该错误
1.下载文章多了就卡住不动了，我刷新微信公众号没有【访问频繁】的情况，不知道是软件原因还是微信公众号访问原因？
2.等待时间是不是设置越长越不会出现【频繁】的情况？我设置60秒还是存在卡住不动的情况
3.关闭软件重新下载能不能设置从哪篇文章开始下载？现在软件能支持的就是时间，之前的文章就跳过，可如果篇数过多（超过500篇），即使跳过还是存在卡住不下载的情况。有没有更好的方法可以规避这样的问题？

**Comment by qiye45** [comment]
截图...看看issue，里面都有的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月12日(周三) 凌晨3:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 下载文章多了就卡住了，下次又要重新下载？ (Issue #129)




 
描述该错误
 1.下载文章多了就卡住不动了，我刷新微信公众号没有【访问频繁】的情况，不知道是软件原因还是微信公众号访问原因？
 2.等待时间是不是设置越长越不会出现【频繁】的情况？我设置60秒还是存在卡住不动的情况
 3.关闭软件重新下载能不能设置从哪篇文章开始下载？现在软件能支持的就是时间，之前的文章就跳过，可如果篇数过多（超过500篇），即使跳过还是存在卡住不下载的情况。有没有更好的方法可以规避这样的问题？
