### ISSUE TITLE
新的2.6版 监视剪贴板功能又失效了

### ISSUE THREAD

**Issue by 23456wangyawen** [qiye45/wechatDownload#130]
谢谢解决了下载为空白的问题。但，新的2.6版 监视剪贴板功能（勾选了）仍失效不可用。旧版使用正常。

**Comment by qiye45** [comment]
等下个版本我修一下吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月12日(周三) 下午2:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 新的2.6版 监视剪贴板功能又失效了 (Issue #130)




 
谢谢解决了下载为空白的问题。但，新的2.6版 监视剪贴板功能（勾选了）仍失效不可用。旧版使用正常。

**Comment by qiye45** [comment]
2.7版本修好啦
