### ISSUE TITLE
Mac 版本获取公众号 id 是灰色的无法点击

### ISSUE THREAD

**Issue by rap16** [qiye45/wechatDownload#132]
Mac 版本获取公众号 id 是灰色的无法点击
![image](https://github.com/qiye45/wechatDownload/assets/25992910/72227629-953f-4b6c-bf14-2dabe76242f6)

**Comment by qiye45** [comment]
因为还没适配，试试用文章下载咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月14日(周五) 晚上6:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] Mac 版本获取公众号 id 是灰色的无法点击 (Issue #132)




 
Mac 版本获取公众号 id 是灰色的无法点击
 image.png (view on web)

**Comment by aaron-codes** [comment]
+1 mac  无法点击

**Comment by skyding717** [comment]
那只有等下一个版本了

**Comment by nevertoday** [comment]
这个版本不打算更新了？
