### ISSUE TITLE
自定义下载时间不起作用

### ISSUE THREAD

**Issue by huke123456** [qiye45/wechatDownload#133]
描述该错误
下载到2021年左右的时候，提示等待20s, 实际一直等待，重新打开用自定义下载时间，截止至2021，程序仍然从2024开始扫描并跳过下载。这样是不是浪费时间？ 
如果是自定义的话，是不是应该从最后的2021年开始往前下载？

**Comment by qiye45** [comment]
后面会加上跳过下载的 https://github.com/qiye45/wechatDownload/issues/72

**Comment by qiye45** [comment]
2.7支持延续上次下载啦
