### ISSUE TITLE
怎么打开软件

### ISSUE THREAD

**Issue by Triplemode100** [qiye45/wechatDownload#135]
下载完压缩包后，不知道怎么打开软件。
![image](https://github.com/qiye45/wechatDownload/assets/173069005/467b9078-ee01-4ffd-a378-2544cdb925f4)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
在这里 https://github.com/qiye45/wechatDownload/releases ...

**Comment by Triplemode100** [comment]
谢谢指路，但是下载单个文件，无法成功下载pdf和word，只有网页。
![image](https://github.com/qiye45/wechatDownload/assets/173069005/fc73261f-4145-47b5-af68-613a1d2c469c)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/42
