### ISSUE TITLE
软件一直无法获取秘钥

### ISSUE THREAD

**Issue by azz212** [qiye45/wechatDownload#136]
描述该错误
对该错误的简明扼要的描述。
按照操作，复制一片文章，点击获取公众号ID，然后将返回的历史记录的链接在微信里面发送到文件助手，然后点击在内置浏览器中打开。软件一直无法获取秘钥
截图
添加截图以帮助解释你的问题。

其他信息
试了多个公众号，没有开tz，不同微信版本也试了

**Comment by qiye45** [comment]
换台电脑试一试咯

**Comment by azz212** [comment]
为啥跟电脑有关啊？到底是什么原因导致的？

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/9

**Comment by azz212** [comment]
这个都看了，该避雷的都避了
