### ISSUE TITLE
批量下载几篇后就闪退

### ISSUE THREAD

**Issue by FeynmanHung** [qiye45/wechatDownload#137]
**描述该错误**
按照正常的点击流程，默认选项之下点击批量下载，没几篇之后就闪退。
系统是win11，微信版本是3.9.11.15，用的作者的版本是2.7，之前好几个版本都用过，情况都一样[sad]。
下载的公众号是这个：https://mp.weixin.qq.com/s/IxHk9YuG547LTjiW4hHBHw

**截图**

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
我试试 Σ( ° △ °|||)︴



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月18日(周二) 中午1:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 批量下载几篇后就闪退 (Issue #137)




 
描述该错误
 按照正常的点击流程，默认选项之下点击批量下载，没几篇之后就闪退。
 系统是win11，微信版本是3.9.11.15，用的作者的版本是2.7，之前好几个版本都用过，情况都一样[sad]。
 下载的公众号是这个：https://mp.weixin.qq.com/s/IxHk9YuG547LTjiW4hHBHw
 
截图
 
其他信息
 在这里添加关于该问题的任何其他背景。

**Comment by inroading** [comment]
win11，的确有这个问题，频频闪退，不论导出什么格式，即使不导出，也是几分钟就闪退

**Comment by qiye45** [comment]
试试旧版本会闪退吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月19日(周三) 上午10:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 批量下载几篇后就闪退 (Issue #137)




 
win11，的确有这个问题，频频闪退，不论导出什么格式，即使不导出，也是几分钟就闪退

**Comment by inroading** [comment]
2.6和2.7都会闪退，可以下载及导出，下载一般在20条左右闪退，导出的excel一般10-11条记录

**Comment by qiuzhen8484** [comment]
win11同闪退

**Comment by qiye45** [comment]
奇怪，好像win11特有的问题(・∀・(・∀・(・∀・*)

**Comment by cccan3** [comment]
win10也有这个问题，我是win10家庭版，微信3.9.10.19也是批量下载就闪退

**Comment by alexchanjy** [comment]
确实，我的环境是windows10企业版，微信3.9.11.17；换了三台电脑，环境都一样，都闪退

每个公众号第一次批量的时候大概20-30篇闪退，随后再启动基本上3-4篇就闪退；

**Comment by codeveronicaart** [comment]
win11,只要把工具切到后台,几秒内必闪退.
如果保持工具在前台,且不做任何其它操作时,就基本不会闪退,但是,在下载一定量的文章之后,就会无限循环随机暂停xx秒...

**Comment by jiaochenglong** [comment]
相同的问题 Windows 10 专业版 22H2 ，插个眼

**Comment by qiye45** [comment]
试试保持软件前台

**Comment by ws-glitch** [comment]
同样出现这个问题，公众号文章比较多，下到2022年的文章总是闪退，win11,2.7版本，设置了兼容模式也不行

**Comment by shaojiahao** [comment]
遇到同样的问题，V2.6和V2.7都一样，表现是正常下载10来20篇，然后软件会自动卡住，过十来秒窗口就消失了

**Comment by KAHO-TONG** [comment]
信息窗口反复提示暂停下载，暂停多几次就完全停止了。

**Comment by qiye45** [comment]
等3.0版本更新吧，应该修复闪退啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月7日(周日) 凌晨0:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 批量下载几篇后就闪退 (Issue #137)




 
信息窗口反复提示暂停下载，暂停多几次就完全停止了。

**Comment by Liu8Can** [comment]
同样的win11闪退

**Comment by hehelaughs** [comment]
win10保持前台，也只能下载几分钟，然后闪退，pdf还没下载

**Comment by qiye45** [comment]
3.0应该修复闪退问题啦
