### ISSUE TITLE
下载着突然就不继续，卡住了

### ISSUE THREAD

**Issue by boomboom-yang** [qiye45/wechatDownload#138]
像是无限暂停住了，点什么都没用

win10+2.7版本的工具

**Comment by qiye45** [comment]
截图

**Comment by boomboom-yang** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/43577355/d51ed94c-ed43-46a8-84f1-4bd1e45b7cce)

**Comment by qiye45** [comment]
带上链接

**Comment by boomboom-yang** [comment]
https://mp.weixin.qq.com/s/8U-NbOXkX5cDFeXHVEa6hQ
这个是要下载的其中一篇文章，我想要下载该作者的全部文章，然后就卡住了
获取秘钥的主页是这个：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI4NTM5MTU2NQ==&scene=124#wechat_redirect

**Comment by boomboom-yang** [comment]
大佬，还是这个公众号，还会出现新问题，一直都是暂停，重新进或者重新下载依然不会解决，求答疑~

截图如下：
![image](https://github.com/qiye45/wechatDownload/assets/43577355/f29ffdd5-d8fd-4553-954f-358588a64262)

**Comment by PPsteven** [comment]
获取公众号历史消息页面成功，请在微信打开复制的链接：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU1NzY0OTQ3MA==&scene=124#wechat_redirect
开始获取秘钥...
获取秘钥失败...请先在微信打开复制的链接
开始获取秘钥...
获取秘钥成功！请点击下载按钮
为了防止访问公众号被限制，暂停16秒
为了防止访问公众号被限制，暂停18秒
为了防止访问公众号被限制，暂停13秒
为了防止访问公众号被限制，暂停13秒
为了防止访问公众号被限制，暂停12秒
为了防止访问公众号被限制，暂停11秒
为了防止访问公众号被限制，暂停18秒
为了防止访问公众号被限制，暂停15秒
为了防止访问公众号被限制，暂停11秒
为了防止访问公众号被限制，暂停11秒
为了防止访问公众号被限制，暂停19秒
为了防止访问公众号被限制，暂停17秒
为了防止访问公众号被限制，暂停15秒

win10 2.7 最新版本

**Comment by PPsteven** [comment]
> 获取公众号历史消息页面成功，请在微信打开复制的链接：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU1NzY0OTQ3MA==&scene=124#wechat_redirect 开始获取秘钥... 获取秘钥失败...请先在微信打开复制的链接 开始获取秘钥... 获取秘钥成功！请点击下载按钮 为了防止访问公众号被限制，暂停16秒 为了防止访问公众号被限制，暂停18秒 为了防止访问公众号被限制，暂停13秒 为了防止访问公众号被限制，暂停13秒 为了防止访问公众号被限制，暂停12秒 为了防止访问公众号被限制，暂停11秒 为了防止访问公众号被限制，暂停18秒 为了防止访问公众号被限制，暂停15秒 为了防止访问公众号被限制，暂停11秒 为了防止访问公众号被限制，暂停11秒 为了防止访问公众号被限制，暂停19秒 为了防止访问公众号被限制，暂停17秒 为了防止访问公众号被限制，暂停15秒
> 
> win10 2.7 最新版本

目前看来，是公众号内容下载完毕后，会一直显示这个消息。我的问题已解决

**Comment by qiye45** [comment]
新版本会延续上次下载的

**Comment by qiye45** [comment]
这样情况应该是下载完了

**Comment by llywjngit** [comment]
您好，请问一下，为什么我批量下载，然后下载完了只有封面和视频，文件全部没有，VPN要关闭吗？还是这么解决
![Uploading 1.jpg…]()
