### ISSUE TITLE
文章中的图片、视频、音频，也希望能离线下载保存到本地

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#140]
导出html时，除文本文字以外，希望能增加选项，可以设置是否同时将文章中的图片、视频、音频，也能离线下载保存到本地。
现在的导出html，好像不能下载图片、视频、音频。都是链接形式。

![image](https://github.com/qiye45/wechatDownload/assets/29511872/b8eaf335-708d-41b9-8a01-350834ce0c33)

**Comment by qiye45** [comment]
已经支持下载图片、视频、音频了 https://github.com/qiye45/wechatDownload/issues/24

**Comment by hrbagang** [comment]
需要额外设置选项吗？
最新的2.7版本，下载的HTML文件，只有2，3百kb，里面没有照图片啊！
看了下HTML内容，里面图片，都是指向服务器链接，并没有指向本地啊？

**Comment by CrossWow** [comment]
最近也发现离线情况下HTML文件里图片“挂了”，上网好解决，主要有个疑虑：如果原文被删除了，是不是HTML备份的也就无效了？！

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/10

**Comment by CrossWow** [comment]
批量下载（HTML，PDF）时，PDF下载不了？！
