### ISSUE TITLE
一直提示：为了防止访问公众号被限制，暂停xx秒

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#141]
**描述该错误**
V2.7，批量下载文章，下载到中途时，一直提示：“为了防止访问公众号被限制，暂停xx秒”，不再继续下载。
文章下载链接：https://mp.weixin.qq.com/s/hwaAmCxLMLUgMGKkzAqcQw

**链接和截图**
![image](https://github.com/qiye45/wechatDownload/assets/29511872/45c2c093-9e8d-49a0-a0d2-bf2594f86dd7)

**Comment by hrbagang** [comment]
重启软件后，重新下载的话，提示：为了防止访问公众号被限制，暂停11秒，不再下载文章。

![image](https://github.com/qiye45/wechatDownload/assets/29511872/58e117b4-8e55-4621-a573-34a53fcb1ac0)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/138
