### ISSUE TITLE
获取公众号ID，打开链接显示：操作频繁，请稍后再试

### ISSUE THREAD

**Issue by Super24Bryant** [qiye45/wechatDownload#142]
文章链接：https://mp.weixin.qq.com/s/_LW8o3L-LCg0sTeHeBXc9A
![微信截图_20240624213833](https://github.com/qiye45/wechatDownload/assets/125115111/e7c247e9-39fc-4be0-a540-f52f7f73bca8)
<img width="1280" alt="微信图片_20240624213842" src="https://github.com/qiye45/wechatDownload/assets/125115111/c50061d7-085f-4aed-a651-a45f95552633">

**Comment by Super24Bryant** [comment]
无法批量下载，但可以一个一个下载

**Comment by qiye45** [comment]
[提示"操作频繁，请稍后再试",如何解决?](https://github.com/qiye45/wechatDownload/issues/78)
