### ISSUE TITLE
下载较久的历史文章有bug

### ISSUE THREAD

**Issue by xiaohushi512** [qiye45/wechatDownload#143]
**描述该错误**
错误1：
下载历史久远一点的，比如23年一整年的文章，因为中间总是断（bug？卡住了），重新退出，如果是之前从当前日期一直批量下载了文章到24年1月1日，那重新启动软件可以直接跳过24年的所有文章，是直接没有提示，不是窗口写着某篇文章跳过下载。但是如果，把setting文件删除后，指定日期23年1月1日到23年12月31日，又要重新从当天日期一篇一篇的检查跳过下载。
错误2：
批量下载久远一点的历史文章23年一整年，比如窗口卡住了不下载了（经常卡，反正我就没试过一次能完整的下载过某一年的文章，都是搞三四次），窗口的提示文章卡在6月1日，但后台可能继续去读取到了5月15日，卡住了，关闭后，重新下载23年一整年的文章，前面的12月31日到6月1日的文章直接跳过，但是5月31日到5月16日的文章没下载，从5月14日开始下载。中间少了很多。

功能建议：
文章前面加日期前缀，能不能再加个-，把日期和文章隔开，因为有些文章标题是数字开头的，就导致某些文章直接变成不是按日期了，跑到最后面去了。

**其他信息**
win10，2.7

**Comment by qiye45** [comment]
带上链接和截图

**Comment by laotumsn** [comment]
下载历史文章程序的确会卡死，然后自动退出，重新双击打开之后只有图标界面弹不出来。只有在任务管理器里结束进程之后才能重新打开，是不是多线程有点问题？

**Comment by qiye45** [comment]
试试保持软件在前台 https://github.com/qiye45/wechatDownload/issues/137#issuecomment-2194369919

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/137 啦
