### ISSUE TITLE
能否批量获取某一公众号一段时间内所有文章的标题

### ISSUE THREAD

**Issue by QQ080703** [qiye45/wechatDownload#144]
一篇一篇地复制太麻烦了

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/65

**Comment by kevinZheng13** [comment]
为啥看不到工具从哪下载呢

**Comment by QQ080703** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiye45/wechatDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qiye45/wechatDownload] 能否批量获取某一公众号一段时间内所有文章的标题 (Issue #144)





 
为啥看不到工具从哪下载呢

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/releases
