### ISSUE TITLE
可否循环批量下载单篇文章里面的图片？

### ISSUE THREAD

**Issue by always-dare-to-be-a-beginner** [qiye45/wechatDownload#145]
**描述你想要的功能**

可否循环批量下载单篇文章里面的图片？我想要文章里面的图片
谢谢大神

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/24

**Comment by qiye45** [comment]
pdf或者word里面的图片可以离线保存，试试从里面提取图片

**Comment by always-dare-to-be-a-beginner** [comment]
> pdf或者word里面的图片可以离线保存，试试从里面提取图片

确实，我咋没想到呢
