### ISSUE TITLE
批量下载时突然报错

### ISSUE THREAD

**Issue by Andy-AO** [qiye45/wechatDownload#146]
![image](https://github.com/qiye45/wechatDownload/assets/38101170/b870f333-3216-40b2-a469-de743ecf96bc)

https://mp.weixin.qq.com/s/98ua28hLKQHPRyi0FAc5JQ

https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzA4NjI3OTY4Mg==&scene=124#wechat_redirect

**Comment by qiye45** [comment]
奇怪了，系统环境是什么
