### ISSUE TITLE
2.6macos版本，点不了【获取id】，无论是输入了网站，还是没输入。

### ISSUE THREAD

**Issue by clairemaidou** [qiye45/wechatDownload#147]
![Screenshot 2024-06-30 at 17 41 26](https://github.com/qiye45/wechatDownload/assets/174241823/305916d7-5df2-40e7-acde-8a2364985413)
2.6macos版本，点不了【获取id】，无论是输入了网站，还是没输入。

**Comment by qiye45** [comment]
mac版本还没支持，用文章下载咯

**Comment by CAROLINE12312312** [comment]
up你好: 是不是意味着Mac 还不能批量下载文件哇  只能一个个复制链接然后下载

**Comment by qiye45** [comment]
是滴

**Comment by nixyme** [comment]
请问近期有支持mac的计划么？
