### ISSUE TITLE
微信3.9.11.17获取秘钥失败

### ISSUE THREAD

**Issue by xjh1994** [qiye45/wechatDownload#149]
描述该错误
微信3.9.11.17获取秘钥失败...请先在微信打开复制的链接

链接和截图
![image](https://github.com/qiye45/wechatDownload/assets/3397116/12b8c2f6-5b67-4142-9b85-9e5287918091)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
看看#9



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月1日(周一) 晚上9:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 微信3.9.11.17获取秘钥失败 (Issue #149)




 
描述该错误
 微信3.9.11.17获取秘钥失败...请先在微信打开复制的链接
 
链接和截图
 image.png (view on web)
 
其他信息
 在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/9#issuecomment-2306036591
