### ISSUE TITLE
获取公众号ID和批量下载都是置灰的

### ISSUE THREAD

**Issue by mc0919** [qiye45/wechatDownload#151]
描述该错误
获取公众号ID和批量下载都是置灰的

链接和截图
<img width="990" alt="image" src="https://github.com/qiye45/wechatDownload/assets/9820018/f140d605-7fa0-4e13-90b4-31da27103e4d">

其他信息
macOS 15 版本15.0 Beta版(24A5279h)
m1

**Comment by qiye45** [comment]
Pro版本解锁全功能，可以考虑一下哟 https://t.me/changfengboxchat/1614
