### ISSUE TITLE
选择时间bug

### ISSUE THREAD

**Issue by MiloMMIN** [qiye45/wechatDownload#152]
**描述该错误**
似乎选择时间了之后点批量下载，不是在想要的时间内开始，而且下不下来

**链接和截图**
添加链接和截图以帮助解释你的问题。
![image](https://github.com/qiye45/wechatDownload/assets/143987911/c3e8ca30-d9e7-43bd-a08b-14e9ce2c48b8)

**其他信息**
win10专业版 软件2.7版本的

**Comment by qiye45** [comment]
选一个月内就好了

**Comment by Eyion** [comment]
占楼提个建议，可以提供其他网盘吗？夸克注册登录了还得存自己盘才能下载，在github下载也比夸克强。

**Comment by qiye45** [comment]
因为作者要吃饭滴 ＞﹏＜

**Comment by Eyion** [comment]
原来如此，懂了
