### ISSUE TITLE
自定义时间下载-3.0闪退

### ISSUE THREAD

**Issue by xiaohushi512** [qiye45/wechatDownload#154]
**闪退**
自定义时间，2019年如下图。话说，那个开始下载页数，哪里看，微信文章历史文章没有页数的显示啊！
获取id后，点击批量下载就直接闪退了。

**链接和截图**
![360截图20240710202814944](https://github.com/qiye45/wechatDownload/assets/118704402/192a1a7e-36a1-4094-9fdd-6eab04aa8062)
https://mp.weixin.qq.com/s/wifCKFKUzOD3BsRJnwl9Zg)

**其他信息**
win10专业版22H2，3.0

**Comment by KAHO-TONG** [comment]
遇到同上问题

**Comment by qiye45** [comment]
奇怪了win10正常呢 ![image](https://github.com/qiye45/wechatDownload/assets/138199658/e62f8fa8-804e-4967-af0c-e0ab62a9ccaf)

**Comment by qiye45** [comment]
一页有10篇，开始下载页数1，表示从第10篇开始下载，开始下载页数2，表示从第20篇开始下载

**Comment by qiye45** [comment]
发一下链接吧

**Comment by 52githubCode** [comment]
> 奇怪了win10正常呢 ![image](https://private-user-images.githubusercontent.com/138199658/347706419-e62f8fa8-804e-4967-af0c-e0ab62a9ccaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE4NjYsIm5iZiI6MTcyMjQyMTU2NiwicGF0aCI6Ii8xMzgxOTk2NTgvMzQ3NzA2NDE5LWU2MmY4ZmE4LTgwNGUtNDk2Ny1hZjBjLWUwYWI2MmE5Y2NhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMDI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzkxNDMxMGQ3ZjMyMzcyZTBlOTIzY2E4ODk0NmJiNjVkODYxMTAzNzA4OTRjODg0YTAyNmU3NWZkNjY4OGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wx21LEXUJhLueq6g5KfBmeCGg5uX4JWRA91_Lcf7VHo) ![image](https://private-user-images.githubusercontent.com/138199658/347706648-bd7c4f93-7629-4a40-aaee-1aad2de83ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE4NjYsIm5iZiI6MTcyMjQyMTU2NiwicGF0aCI6Ii8xMzgxOTk2NTgvMzQ3NzA2NjQ4LWJkN2M0ZjkzLTc2MjktNGE0MC1hYWVlLTFhYWQyZGU4M2FlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMDI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmUzZjYzZDMyMTAyMzQzZTRiZWUwZjdkOWE5NTdiZWZmYWE3YzA4MmE2ZjVjMjljZWEzNjA5NzcyZThiYzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.netPQI8D9fK8koCSr0sFCyYPjxLqrgvwvrIepW5C_SY) ![image](https://private-user-images.githubusercontent.com/138199658/347781397-f2ce20f8-a08c-4a38-afd2-429acfb401c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE4NjYsIm5iZiI6MTcyMjQyMTU2NiwicGF0aCI6Ii8xMzgxOTk2NTgvMzQ3NzgxMzk3LWYyY2UyMGY4LWEwOGMtNGEzOC1hZmQyLTQyOWFjZmI0MDFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMDI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjQ2MzAxZmNkMDVlYjUzYmQ2OGZlYzExZWM4MzNlMTc1OTlhMWZlZjFkOWFiMDE2ZTQwNjdiNzA0YTQ4NTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LoGO-EOv2oc9_czq3TzO9Gv0JN0wEKBynxcUhHgJj1Q)

你这里没指定时间吧，楼上是指定了时间闪退
