### ISSUE TITLE
能否提供夸克网盘之外的下载路径

### ISSUE THREAD

**Issue by dengyakui** [qiye45/wechatDownload#155]
描述该错误
由于机器环境限制, 无法安装夸克网盘,并且不充值VIP的话下载限速, 能否直接用 Github 自带的Release下载或阿里盘来下载

**Comment by qiye45** [comment]
因为作者要恰饭滴 ＞﹏＜
注册个夸克账号咯

**Comment by dengyakui** [comment]
> 因为作者要恰饭滴 ＞﹏＜ 注册个夸克账号咯

👌
