### ISSUE TITLE
每次运行到一半就会卡住，之后再启就会闪退

### ISSUE THREAD

**Issue by Menmadiss** [qiye45/wechatDownload#157]
3.0/2.2/2.6/2.7多版本尝试都会这样
Windows 11 专业版
电脑重启，微信重启都尝试过，放置前台运行也尝试了

**Comment by Menmadiss** [comment]
> 3.0/2.2/2.6/2.7多版本尝试都会这样 Windows 11 专业版 电脑重启，微信重启都尝试过，放置前台运行也尝试了

之后每次都只能按照指定时间运行，然后又从头运行，还没运行到指定时间就闪退了

**Comment by qiye45** [comment]
录个视频看看

![image](https://github.com/user-attachments/assets/96feaa93-1d60-4d27-aa99-2aaa7fd99845)
![image](https://github.com/user-attachments/assets/e778faa5-779d-40a5-95a7-a8f14ab465d6)

**Comment by Menmadiss** [comment]
Uploading 1.mp4…

**Comment by Menmadiss** [comment]
https://github.com/user-attachments/assets/0528fc7c-30d7-4ff7-b6ca-f16475c5bbf5

就是这样 卡住了 换了个微信也卡住了

**Comment by qiye45** [comment]
试试单篇下载能下载吗

**Comment by dengyakui** [comment]
我也有这个问题， 第一次运行时，选择的下载全部，过一段时间停止了， 然后后续重新打开程序，选择自定义时间段下载就闪退
![image](https://github.com/user-attachments/assets/2b6d2aed-832d-40bc-bfa4-205d34c30f24)

**Comment by Menmadiss** [comment]
> 试试单篇下载能下载吗

可以的

**Comment by myaijarvis** [comment]
win11 使用3.0也闪退，运行下载几分钟后就自动闪退了，试了好几次都这样，2.4的就没事

**Comment by smallBG** [comment]
win10 使用3.0也闪退，单篇下载没事

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/164 啦
