### ISSUE TITLE
获取的历史文章访问异常

### ISSUE THREAD

**Issue by xiaohushi512** [qiye45/wechatDownload#162]
**描述该错误**
获取的文章链接，提交给Kimi访问浓缩要点，提示环境异常

**链接和截图**
![360截图20240719224427549](https://github.com/user-attachments/assets/83f0396a-986c-4d3d-bce5-f93df80d0619)

http://mp.weixin.qq.com/s?__biz=Mzg2NDEzNTk4OA==&amp;mid=2247612480&amp;idx=2&amp;sn=87c4afc702b4c3a4ea05262e9c9e191d&amp;chksm=ce6e861bf9190f0d499c143b17f136354457c8e1d0e655a386b6586ab8a32d5252cba69e3b47&amp;scene=27#wechat_redirect
浏览器打不开文章链接，点击认证后也是不成功，不能访问链接的

**其他信息**
2.7下载的Excel表内文章链接，360浏览器，win10专业版

**Comment by LeonNadal** [comment]
你的链接可以正常打开，你现在可以正常采集文章吗，我的前几天能用，现在用不了了

**Comment by mundane799699** [comment]
> **描述该错误** 获取的文章链接，提交给Kimi访问浓缩要点，提示环境异常
> 
> **链接和截图** ![360截图20240719224427549](https://private-user-images.githubusercontent.com/118704402/350438804-83f0396a-986c-4d3d-bce5-f93df80d0619.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODg0MzksIm5iZiI6MTcyMTQ4ODEzOSwicGF0aCI6Ii8xMTg3MDQ0MDIvMzUwNDM4ODA0LTgzZjAzOTZhLTk4NmMtNGQzZC1iY2U1LWY5M2RmODBkMDYxOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxNTA4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTc5MjE5NTkyZTA5Mzg4N2E5YjkwYjUxN2FiMjAxOTUwMmMxY2NkZWE1Y2ZiYzY0ZDUwY2Q4Zjc5NGVmYWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C3u8JHQp_az8GrFj1xiSV4yX_2qpCYxc2-xf-Tr48Cs)
> 
> http://mp.weixin.qq.com/s?__biz=Mzg2NDEzNTk4OA==&amp;mid=2247612480&amp;idx=2&amp;sn=87c4afc702b4c3a4ea05262e9c9e191d&amp;chksm=ce6e861bf9190f0d499c143b17f136354457c8e1d0e655a386b6586ab8a32d5252cba69e3b47&amp;scene=27#wechat_redirect浏览器打不开文章链接，点击认证后也是不成功，不能访问链接的
> 
> **其他信息** 2.7下载的Excel表内文章链接，360浏览器，win10专业版

把所有&amp;替换成&。
http://mp.weixin.qq.com/s?__biz=Mzg2NDEzNTk4OA==&mid=2247612480&idx=2&sn=87c4afc702b4c3a4ea05262e9c9e191d&chksm=ce6e861bf9190f0d499c143b17f136354457c8e1d0e655a386b6586ab8a32d5252cba69e3b47&scene=27#wechat_redirect

**Comment by qiye45** [comment]
微信那边升级了，等3.1新版本咯
![image](https://github.com/user-attachments/assets/5062bdb5-4512-4db7-9eba-e4f0200c68ae)

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/161 啦
