### ISSUE TITLE
3.1版本还是获取不到id

### ISSUE THREAD

**Issue by a734630653** [qiye45/wechatDownload#164]
**描述该错误**
3.1版本还是不能批量下载，获取不到id

**链接和截图**

**其他信息**
重启电脑好几次了，还是不行。

**Comment by hijos** [comment]
我是获取成功后软件就闪退了

**Comment by ShixishengNiushu** [comment]
刚刚更新了，获取不到秘钥

**Comment by MiGZhuo** [comment]
同上，获取密匙失败

**Comment by Leo6662008** [comment]
更新到3.1，win10和win11都获取不了秘钥。win11版本21h2，管理员运行点击获取公众号id后闪退。。。
以前2.7win10能正常使用，现在也不行了，是不是微信更新才用不了。。。

**Comment by qiye45** [comment]
截图

**Comment by a734630653** [comment]
![Uploading PixPin_2024-07-23_20-58-47.png…]()

**Comment by a734630653** [comment]
![PixPin_2024-07-23_20-58-47](https://github.com/user-attachments/assets/f741d97a-4fc7-4750-9556-34e38ef2a6fa)

**Comment by hijos** [comment]
> 截图

我是填入链接后点“获取公众号id”，之后提示获取成功
![image](https://github.com/user-attachments/assets/1f8f7ace-f7dd-4ad6-a90d-cd6b0346c0e7)
然后我再去打开微信，一打开微信后，软件就马上闪退了

**Comment by LeonNadal** [comment]
> 截图

更新后的第二天用正常，不知为啥现在用(26号)又不正常了，出现的现状是一直提示获取，然后失败，而且不像之前那样提示的频率比较慢，而是很快的就循环提示了获取、失败、获取.....

**Comment by qiye45** [comment]
因为微信升级了风控，可能会失败

**Comment by qiye45** [comment]
win10没问题的
![image](https://github.com/user-attachments/assets/e3c8e87e-24f4-4b57-97e0-ca9fcfc2d97a)

**Comment by nevertoday** [comment]
macos 完全没有这些功能吧

**Comment by WUYI-JJ** [comment]
我换了一个电脑之后可以采获取秘钥采集，但是这个电脑怎么样都没办法获取秘钥，有谁知道这是什么原因吗

**Comment by WUYI-JJ** [comment]
> 我换了一个电脑之后可以采获取秘钥采集，但是这个电脑怎么样都没办法获取秘钥，有谁知道这是什么原因吗

过了一夜又不好使了

**Comment by qiye45** [comment]
> macos 完全没有这些功能吧
有Mac版本
![image_2024-07-05_21-36-04](https://github.com/user-attachments/assets/0b9533f4-5d8e-476a-ba7a-7c15e1cc13cc)

**Comment by qiye45** [comment]
下载闪退可能因为秘钥过期了，重新获取就好啦，可以接着上次下载的进度，继续下载哒

**Comment by WUYI-JJ** [comment]
> 因为微信升级了风控，有可能会失败

您好，像一直获取秘钥失败这种情况，有什么办法处理吗

**Comment by IceCola** [comment]
我的win11这两天获取密钥成功，开始批量下载时，会闪退，什么都下不下来。前天试的时候还一切正常能下载。

**Comment by IceCola** [comment]
我的win11这两天获取密钥成功，开始批量下载时，会闪退，什么都下不下来。前天试的时候还一切正常能下载。

**Comment by PiKa5623** [comment]
还是不行啊  是不是微信在搞鬼啊 尝试了旧版本的微信还是不行

**Comment by nevertoday** [comment]
> > macos 完全没有这些功能吧
> 
> 有Mac版本 ![image_2024-07-05_21-36-04](https://private-user-images.githubusercontent.com/138199658/352696964-0b9533f4-5d8e-476a-ba7a-7c15e1cc13cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzQ0MjgsIm5iZiI6MTcyMjE3NDEyOCwicGF0aCI6Ii8xMzgxOTk2NTgvMzUyNjk2OTY0LTBiOTUzM2Y0LTVkOGUtNDc2YS1iYTdhLTdjMTVlMWNjMTNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMzQyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmEzMGEzMmY5OTcyMjExNjU1ZmZiOWE4NTEyOTIxZTEyZjI5YjViNWFmOTdmODY1MDg1YzVmZGJjNjA2OWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h0Y35pm0X-TNJXyShdPTqwCjnyMuIt6RNFaLZIIlFwE)

并谬有获取到下载3.0 macos 版本哦~ 我看了分享的文件夹中并没有macos 版本，是么？

**Comment by mundane799699** [comment]
建议作者搞个记录日志功能吧，把闪退的日志记录下来。然后在软件里做个按钮，点击按钮以后打开保存日志的目录。这样用户就可以把日志发给作者了，方便排查问题。光是看截图是看不出什么东西的。
![Snipaste_2024-07-29_13-28-39](https://github.com/user-attachments/assets/bb97e1e5-237d-4534-b43c-b797512f85e9)

**Comment by WUYI-JJ** [comment]
> 建议作者搞个记录日志功能吧，把闪退的日志记录下来。然后在软件里做个按钮，点击按钮以后打开保存日志的目录。这样用户就可以把日志发给作者了，方便排查问题。光是看截图是看不出什么东西的。 ![Snipaste_2024-07-29_13-28-39](https://private-user-images.githubusercontent.com/17701628/352924411-bb97e1e5-237d-4534-b43c-b797512f85e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDU3ODgsIm5iZiI6MTcyMjI0NTQ4OCwicGF0aCI6Ii8xNzcwMTYyOC8zNTI5MjQ0MTEtYmI5N2UxZTUtMjM3ZC00NTM0LWI0M2MtYjc5NzUxMmY4NWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA5MzEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjA1NmFhMTEwODIyMzM1ZTU5ZTk3MmE0MTRlMjhkNjBkZTQ2MmE3NmE3ZGNjMjk4Mzc2NWU4YmNlY2NiZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a9vVKRS1Ned0iaT0MwoZHULDEs4J6lk54rKnwgA8aYI)

你这个是什么呀

**Comment by WJ-great** [comment]
获取下载地址后，开始下载时，一直提示密钥获取失败

**Comment by a185039136** [comment]
![微信截图_20240731102547](https://github.com/user-attachments/assets/c4b251ac-0e91-4b36-831e-0797f853481d)
一直提示密钥获取失败

**Comment by WUYI-JJ** [comment]
你们现在获取秘钥有成功吗

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/174 啦
