### ISSUE TITLE
Mac 版的 3.1 什么时候有呀？

### ISSUE THREAD

**Issue by zengboin** [qiye45/wechatDownload#166]
希望有 Mac 版的 3.1

**Comment by qiye45** [comment]
Mac可以购买Pro版本哟，解锁mac的全功能

**Comment by nevertoday** [comment]
也不知道怎么才能联系上

**Comment by qiye45** [comment]
加我微信吧 changfeng998a

**Comment by 10179013** [comment]
这个微信号changfeng998a加不上了，有其他联系方式吗，我也想买 解锁mac的全功能

**Comment by qiye45** [comment]
加我tg吧 https://t.me/changfeng998
