### ISSUE TITLE
好用

### ISSUE THREAD

**Issue by qfs1987** [qiye45/wechatDownload#168]
就是文件的时间命名好像有点不对
而且下载后的公众号文章排版丢失了时间，不然可以通过发表时间查看的

**Comment by WUYI-JJ** [comment]
> 就是文件的时间命名好像有点不对 而且下载后的公众号文章排版丢失了时间，否则可以通过发表时间查看的

你的可以正常使用呀，你用了几天呀

**Comment by symorning** [comment]
> 就是文件的时间命名好像有点不对 而且下载后的公众号文章排版丢失了时间，不然可以通过发表时间查看的

老哥电脑是win几，用的哪个版本嘞？我之前可以使用，但现在win11的2.567都密钥失败
