### ISSUE TITLE
指定时间批量下载文章，软件会闪退

### ISSUE THREAD

**Issue by 52githubCode** [qiye45/wechatDownload#170]
**描述该错误**
第一次批量下载文章，公众号的历史文章只能下载一部分就**自动停止**下载了，**再次**批量下载文章并**指定时间**，软件会**闪退**
**链接和截图**
![获取公众号id-success](https://github.com/user-attachments/assets/2cef7182-8011-4e24-a422-6de27f184add)
![获取公众号密钥-success](https://github.com/user-attachments/assets/10595207-6789-4a7d-8181-2232e28625fe)
![再次批量下载](https://github.com/user-attachments/assets/32f62eb5-712c-44bb-b052-1b8fa080227b)
![再次批量下载-开始下载](https://github.com/user-attachments/assets/edbf2ec4-a3e9-48fa-874e-ee23a3f9aba9)

然后闪退...

其他信息
上述情况在**复现时**还遇到了**新问题**，软件不闪退，但是**一直卡在** 起始下载页数
![再次批量下载-多次下载](https://github.com/user-attachments/assets/6d283d08-e959-4fdc-8930-855b2e371687)

**Comment by 52githubCode** [comment]
win10, 软件版本3.1

**Comment by qiye45** [comment]
发一下链接吧

**Comment by WUYI-JJ** [comment]
现在获取秘钥不会失败了吗，我这面怎么还是一直失败，链接：https://mp.weixin.qq.com/s/BiVWEOZzNgDBaw9N-KxBZw
![103801738ee70fa9393cbcd86c52bd4](https://github.com/user-attachments/assets/188d4608-9084-4475-b08f-9869d197d009)

![Uploading aa9bbbc762be82b04c12dc69113bc20.png…]()

**Comment by 365jours** [comment]
![image](https://github.com/user-attachments/assets/b7181f9f-838c-4a20-bc52-97d4103a79b9)
自定义时间批量下载一直卡在起始页，没动静，试了下按天、月、年的都一样无法奏效。只有单篇文章下载可行。

**Comment by 365jours** [comment]
这是文章链接：https://mp.weixin.qq.com/s/gGrUfKXEdpEq5XfSG96m8g

**Comment by pros2021** [comment]
我这问题和楼主得截图一样，下载很多文章后，就不再下载了。

**Comment by qiye45** [comment]
好像自定义时间确实有些问题

**Comment by qiye45** [comment]
3.2版本应该修复自定义时间啦
![image](https://github.com/user-attachments/assets/bc301454-c93e-443b-bb98-caddadddc7ee)
