### ISSUE TITLE
3.1版本无法获取key

### ISSUE THREAD

**Issue by fanyao1983** [qiye45/wechatDownload#174]
微信版本是3.9.10.16
按照操作说明都做了,就是无法获取

**Comment by loserzero-7** [comment]
我也是，用了最新版的不行，换了3.9.11.25也不行

**Comment by qiye45** [comment]
试试WeChatSetup-3.9.10.27的

**Comment by IceCola** [comment]
供参考：
· win11+最新版微信，获取不到密钥。
· 然后虚拟机装了win10+WeChatSetup-3.9.10.27，能够获取密钥，正常下载了。

**Comment by qiye45** [comment]
附上WeChatSetup-3.9.10.27啦 https://github.com/qiye45/wechatDownload/releases/tag/3.1

**Comment by WUYI-JJ** [comment]
> 供参考：
> 
> * win11+最新版微信，获取不到密钥。
> * 然后尝试用虚拟机VMware装了win10+WeChatSetup-3.9.10.27，能够获取密钥，正常下载了。
>   · 有一个小问题，下载开始了到最后会强退，但看了一下下载已经完成了，所以没有太大影响
> 
> 另外历史版本微信可以在这里下载：![1723331154446](https://github.com/user-attachments/assets/36c3e5a6-0c21-4e22-b48d-afbd1f5b05ea)  我的就是win10，也安装了WeChatSetup-3.9.10.27 还是不行，你采集工具用的是3.1版本的吗

**Comment by LeonNadal** [comment]
> 供参考：
> 
> * win11+最新版微信，获取不到密钥。
> * 然后尝试用虚拟机VMware装了win10+WeChatSetup-3.9.10.27，能够获取密钥，正常下载了。
>   · 有一个小问题，下载开始了到最后会强退，但看了一下下载已经完成了，所以没有太大影响
> 
> 另外历史版本微信可以在这里下载：https://github.com/tom-snow/wechat-windows-versions

这个可行，使用虚拟机的时候，我也遇到了像你一样闪退的问题(应该是采集特定文章会遇到程序自身的报错，每次开始采集这一篇文章的情况下，就会闪退)，如果你再次按流程进去下载，到了上次采集到同一个文章闪退的那篇文章照样会闪退，这个可以通过跳过页面解决，并且需要删除之前已经下载的数据。关于跳过的也可以试一下通过限定时间

**Comment by zhou828** [comment]
工具3.1+微信3.9.9.43/3.9.10.27都不行，操作系统win11

**Comment by yangzec** [comment]
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect
出现这个问题

**Comment by zhou828** [comment]
> https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect 出现这个问题

_biz在cookies里面能查到，但是补充到这个URL里面也没用，软件获取不到密钥

**Comment by qiye45** [comment]
等下个版本我修一下吧

**Comment by IceCola** [comment]
> 等下个版本我修一下吧

一样遇到了这个问题。感谢大佬fix！

**Comment by qiye45** [comment]
先试试旧的文章，是不是正常吧

**Comment by JayeeDu** [comment]
> 等下个版本我修一下吧

请问下个版本大概什么时候啊？

**Comment by mumuxi-git** [comment]
> https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect 出现这个问题

遇到同样的问题...

**Comment by pros2021** [comment]
> https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect 出现这个问题

一样遇到了这个问题。

**Comment by qiye45** [comment]
试试用公众号旧一点的文章来获取公众号id

**Comment by tinyboa** [comment]
WeChatSetup-3.9.10.27版本可用，但是使用一段时间后，又会出现无法获取key的情况，估计是X讯通过在线方式打补丁了，即使不选择升级新版微信也是这样，解决办法是用CleanMyPC这款软件卸载微信客户端，直接卸载估计会有注册表或者缓存残留，不建议。重新安装WeChatSetup-3.9.10.27版本可以解决，再次出现无法获取key的情况，重复上述操作即可。系统为Win10 企业版。

**Comment by LeonNadal** [comment]
> WeChatSetup-3.9.10.27版本可用，但是使用一段时间后，又会出现无法获取key的情况，估计是X讯通过在线方式打补丁了，即使不选择升级新版微信也是这样，解决办法是用CleanMyPC这款软件卸载微信客户端，直接卸载估计会有注册表或者缓存残留，不建议。重新安装WeChatSetup-3.9.10.27版本可以解决，再次出现无法获取key的情况，重复上述操作即可。系统为Win10 企业版。

你有遇到这种情况吗。获取公众号历史消息页面成功，请在微信打开复制的链接：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect

**Comment by LeonNadal** [comment]
> 试试用公众号旧一点的文章来获取公众号id

有些公众号提取会有这种情况。【获取公众号历史消息页面成功，请在微信打开复制的链接：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect】然后就算自己手动能把这个正确的拼凑出来，打开后你的应用还是获取不到，可能是因为你的应用监听你给出的这个错误的地址(https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect)，能否加一个框框适配这种手动输入历史文章地址的，后面流程基本一样

**Comment by qiye45** [comment]
3.2应该修复啦
![image](https://github.com/user-attachments/assets/2248ebd1-1856-4b57-bc04-fecaaa776846)
