### ISSUE TITLE
可以将公众号图文原链接嵌入到本地文件中吗

### ISSUE THREAD

**Issue by MisakaMikoto9982** [qiye45/wechatDownload#176]
如题，我用过好几年这类下载器，很多软件标配此功能，如吾爱破解@夜泉的“WeChatDownload”、本站xiaoguyu的“wechatDownload”，希望咱们这款软件也支持它，谢谢
https://github.com/xiaoguyu/wechatDownload
https://www.52pojie.cn/thread-641714-1-1.html
https://www.52pojie.cn/thread-747580-1-1.html
![图片](https://github.com/user-attachments/assets/f69f10f7-6846-4137-b773-b9af012cae28)

**Comment by qiye45** [comment]
有mhtml下载，支持下载图片的

**Comment by MisakaMikoto9982** [comment]
> 有mhtml下载，支持下载图片的

我是说图片中的“原文地址”，也就是文章本身的链接，而非图片的

**Comment by qiye45** [comment]
下载html有图片的链接的
