### ISSUE TITLE
文件名中添加阅读量，提示前面加上执行的当前时间

### ISSUE THREAD

**Issue by ei0ch** [qiye45/wechatDownload#177]
**描述你想要的功能**
希望能在文件名中添加阅读量，类似“文件开头添加日期”
20240818-*******-10000

**Comment by qiye45** [comment]
用导出表格的功能，这个可以获取阅读量哒

**Comment by getoutboy** [comment]
导出表格功能会闪退哦

**Comment by getoutboy** [comment]
另外能否不用导出表格的形式，因为也会闪退，直接使用导出公众号文章列表html的格式是否可以？而且一次导出后，后面的下载就可以直接使用此html，不容易引起微信的防控措施。谢谢！

**Comment by qiye45** [comment]
保存当前下载的页数在新版本已经加上啦

**Comment by qiye45** [comment]
导出公众号文章列表html复制打开的这个网页就好啦
![image](https://github.com/user-attachments/assets/3fbb19d0-b241-4104-a40f-470c9fc17ebe)

**Comment by getoutboy** [comment]
> 保存当前下载的页数在新版本已经加上啦

非常感谢！另外是否可以在 开始下载提示前面加上执行的当前时间，这样如果卡住了，也能马上看出来，谢谢！

**Comment by qiye45** [comment]
下个版本我加一下运行的时间吧

**Comment by getoutboy** [comment]
非常感谢！
