### ISSUE TITLE
长时间下载自动退出

### ISSUE THREAD

**Issue by fox-404** [qiye45/wechatDownload#179]
**描述该错误**
长时间下载后连接自动退出了，再次进入可以继续

**链接和截图**
https://mp.weixin.qq.com/s/goRklUwFFYSvh1aAE47L-w 此链接的下载

**其他信息**
可以增加一些退出报错以便提示问题

**Comment by qiye45** [comment]
可能因为密钥过期了，有继续下载的功能，重新下载就好啦
