### ISSUE TITLE
批量下载文章获取ID后无法获取秘钥，随后程序自动关闭。

### ISSUE THREAD

**Issue by W-92057** [qiye45/wechatDownload#18]

**Comment by qiye45** [comment]
看看视频教程

**Comment by W-92057** [comment]
使用的是2.2版本，后来换了最新微信客户端可以得到密钥，但还是闪退了








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年2月6日(周二) 晚上9:16写道:

  

 
试试2.2版本

**Comment by qiye45** [comment]
截个图看看吧

**Comment by qiye45** [comment]
最好录个视频

**Comment by W-92057** [comment]
好的，明天早上录个视频，麻烦大佬了








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年2月6日(周二) 晚上9:20写道:

  

 
最好录个视频
