### ISSUE TITLE
3.1批量下载2018年文章程序报错

### ISSUE THREAD

**Issue by tinyboa** [qiye45/wechatDownload#181]
**描述该错误**
批量下载同一公众号文章，至2019年1月都正常，进入2018年12月，程序直接崩溃，Windows提示出现问题，单独下载2018年文章没问题

**链接和截图**
https://mp.weixin.qq.com/s/xllCVWTSNTHhUMi8c7e8bw
起始页数：286，2019年1月分开始跨年

**Comment by qiye45** [comment]
3.2版本应该没问题啦
![image](https://github.com/user-attachments/assets/730c275b-3698-42fc-97ec-38268af1b342)
![image](https://github.com/user-attachments/assets/43f4c759-de4a-4d53-b85a-0adc2ede8f28)
