### ISSUE TITLE
批量下载一段时间，会停止下载，一直提示为防止访问公众号被限制，暂停x秒

### ISSUE THREAD

**Issue by cccan3** [qiye45/wechatDownload#183]
批量下载一段时间，会停止下载，一直提示为防止访问公众号被限制，暂停x秒。
![屏幕截图 2024-09-02 115412](https://github.com/user-attachments/assets/2b5ddd12-e014-4b7b-afbb-52781985f0da)

**Comment by qiye45** [comment]
可能是下载完了

**Comment by qiye45** [comment]
或者密钥过期了，重新获取一下密钥就好啦
