### ISSUE TITLE
无法连接服务器3.2版本

### ISSUE THREAD

**Issue by JefferWong** [qiye45/wechatDownload#186]
**描述该错误**
对该错误的简明扼要的描述。
无法连接服务器
**链接和截图**
添加链接和截图以帮助解释你的问题。
![微信截图_20240904094644](https://github.com/user-attachments/assets/d46a655f-c2b0-44b6-bc41-55a667a76019)
![微信截图_20240904094644](https://github.com/user-attachments/assets/87ceb554-9c4b-4422-ba59-e2c344865bc8)

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
吧梯子关了，或者换个网络试试
