### ISSUE TITLE
下载一段时间后无法继续下载，页面无反应

### ISSUE THREAD

**Issue by cschen3** [qiye45/wechatDownload#187]
![image](https://github.com/user-attachments/assets/e4df9a16-0d80-4689-b14d-f9800938adb2)
获取密钥成功后点击批量下载无反应
![image](https://github.com/user-attachments/assets/9d6617d5-0504-41cc-8845-0dcfc2cc13d2)
下载几次后，获取密钥复制链接无法打开公众号页面，显示频繁操作

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/142
