### ISSUE TITLE
只选择word时，点击文章下载不会导出word

### ISSUE THREAD

**Issue by lukejian003** [qiye45/wechatDownload#188]
**描述该错误**
只选择word时，点击文章下载不会导出word，勾选了html和word就没有问题了

**链接和截图**
添加链接和截图以帮助解释你的问题。

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/42

**Comment by pengyw2020** [comment]
感谢分享，夸克链接失效了，恳请大神补个链接。谢谢

**Comment by qiye45** [comment]
下载链接：https://pan.quark.cn/s/09bdfa78d09b
