### ISSUE TITLE
无法批量下载，一直卡在起始下载页数：0

### ISSUE THREAD

**Issue by pudima** [qiye45/wechatDownload#189]
描述该错误：界面一直卡在起始下载页数：0
对该错误的简明扼要的描述。
大佬你好，昨天还可以正常下载。
今天单篇文章也可以正常下载，但是批量下载失败，能够正常获取公众号id，但是不能点开公众号id链接，显示“操作频繁，请稍后再试”，同时程序运行界面显示获取密钥成功，而后一直卡在起始下载页数：0
链接和截图
![1725527434908](https://github.com/user-attachments/assets/19a11b21-0981-43b5-950c-f25bf8db8cb0)

![1725527416767](https://github.com/user-attachments/assets/fade3f18-ec5d-4d7e-ba02-c69b0ecd4709)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/78

**Comment by pudima** [comment]
好的，好的，谢谢大佬
