### ISSUE TITLE
DOC和PDF格式下载文件夹中内容都为空

### ISSUE THREAD

**Issue by alfreddeng1991** [qiye45/wechatDownload#19]
DOC和PDF格式下载文件夹中内容都为空

**Comment by qiye45** [comment]
选上HTML



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月14日(周三) 中午12:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] DOC和PDF格式下载文件夹中内容都为空 (Issue #19)




 
DOC和PDF格式下载文件夹中内容都为空

**Comment by qiye45** [comment]
此 Issue 被自动关闭，因为它自被标记为过时 stale 以来已闲置。
