### ISSUE TITLE
单篇下载的情况下，公众号图片无法加载

### ISSUE THREAD

**Issue by aike025** [qiye45/wechatDownload#190]
**描述该错误**
对该错误的简明扼要的描述。
单篇下载，图片无法加载，已经尝试1.关掉批量下载工具重新下载
，失败；2.等公众号加载一段时间后再点击单篇下载，失败；
**链接和截图**
公众号链接：https://mp.weixin.qq.com/s/mbLKhfPCkoarhQJBWrsPGA；https://mp.weixin.qq.com/s/isr0DsrqwrP2Oe9AUeIvzQ
![321](https://github.com/user-attachments/assets/bf722790-8c4d-442f-996f-424047f24ac4)；
![123](https://github.com/user-attachments/assets/594ef916-0f10-4204-8753-efeac1568008)；

请教一下，这种情况该怎么解决呢？

**Comment by aike025** [comment]
> **描述该错误** 对该错误的简明扼要的描述。 单篇下载，图片无法加载，已经尝试1.关掉批量下载工具重新下载 ，失败；2.等公众号加载一段时间后再点击单篇下载，失败； **链接和截图** 公众号链接：[https://mp.weixin.qq.com/s/mbLKhfPCkoarhQJBWrsPGA；]
(https://mp.weixin.qq.com/s/mbLKhfPCkoarhQJBWrsPGA%EF%BC%9Bhttps://mp.weixin.qq.com/s/isr0DsrqwrP2Oe9AUeIvzQ) ![321](https://private-user-images.githubusercontent.com/179700551/365231929-bf722790-8c4d-442f-996f-424047f24ac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg3MzAsIm5iZiI6MTcyNTYzODQzMCwicGF0aCI6Ii8xNzk3MDA1NTEvMzY1MjMxOTI5LWJmNzIyNzkwLThjNGQtNDQyZi05OTZmLTQyNDA0N2YyNGFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTczYmY1MzdlNDdlYjg1MDA0MTdhYzRkYTVmZWZjN2U4Mjk2YmU5YjU3M2UyMDQwZTFkOWQ3NGI1YmRjYzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1UxEpYr_3DT8t10r_Z_MkQsqIt8N9Oji2oM1e-KaqaM)； ![123](https://private-user-images.githubusercontent.com/179700551/365231997-594ef916-0f10-4204-8753-efeac1568008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg3MzAsIm5iZiI6MTcyNTYzODQzMCwicGF0aCI6Ii8xNzk3MDA1NTEvMzY1MjMxOTk3LTU5NGVmOTE2LTBmMTAtNDIwNC04NzUzLWVmZWFjMTU2ODAwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWYyYmU1NmVmZWI5NWFhMGQ1M2RlNzE3NmI3OGRhYTQ0YmE2ZjU2N2ZkOWUzZjE3MWYzNmEzMmJkMjYyZGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.981aYJTY7yklZ-DGGnWtM7r5ApZTaGXNmqjaEqiVOEY)；
> 
> 请教一下，这种情况该怎么解决呢？

**Comment by qiye45** [comment]
试试下载mhtml，图片也可以离线保存哒
![image](https://github.com/user-attachments/assets/dc1de453-4eb2-4e79-936c-f6501f008264)

**Comment by qiye45** [comment]
确实有图片无法加载的问题  Σ(ﾟдﾟ;)
![image](https://github.com/user-attachments/assets/5cf7c511-b6b0-47c4-a54c-37c815c32fc3)
