### ISSUE TITLE
进行批量下载，只下载了封面，没有下载文章？

### ISSUE THREAD

**Issue by KingAllen613** [qiye45/wechatDownload#191]
我按照教程安装了软件，获取了公众号ID，也获取了密匙，下载全部的文章的PDF和DOC，但是一直在下载封面，没有下载文章内容，要怎么解决？

**Comment by wuwuzhihong** [comment]
![PixPin_2024-09-09_12-23-18](https://github.com/user-attachments/assets/26819fa2-f9b2-4573-9e3d-d824de3d5b8d)
What happened？

**Comment by wuwuzhihong** [comment]
在历史问题中貌似找到答案了；

**Comment by qiye45** [comment]
按照模板提问题

**Comment by gj009351** [comment]
好像是需要勾选word才可以
