### ISSUE TITLE
一直提示暂停下载，且没有下载行为

### ISSUE THREAD

**Issue by cal-a737** [qiye45/wechatDownload#192]
描述该错误
下载完几篇文章后，开始提示“防止被限制”，暂停20来秒。
然后没有下载行为。

链接和截图

![下载问题](https://github.com/user-attachments/assets/be307204-5889-4e7c-bb0c-5d78bfd7a1c7)
()

其他信息
下载后一直只能下载几篇文章然后就停止了。
后来再重新操作，就出现了以上描述的问题。

**Comment by qiye45** [comment]
带上链接

**Comment by cal-a737** [comment]
重新运行了一下，连接和截图如上图。不断暂停下载

**Comment by qiye45** [comment]
好像没问题
![image](https://github.com/user-attachments/assets/68890fc6-46c0-4b2c-b0a0-3673fe3a3044)
![image](https://github.com/user-attachments/assets/fc663c7e-f07f-4066-87c5-18844c1dbc91)

**Comment by aass0810** [comment]
我现在也是楼主这情况
