### ISSUE TITLE
3.2 版本批量下载只下载第一篇

### ISSUE THREAD

**Issue by hype1type** [qiye45/wechatDownload#193]
**描述该错误**
对该错误的简明扼要的描述。

**链接和截图**
添加链接和截图以帮助解释你的问题。

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by hype1type** [comment]
你是不是在里面塞了快代理的广告？

**Comment by qiye45** [comment]
添加链接和截图以帮助解释你的问题。

**Comment by qiye45** [comment]
添加链接和截图以帮助解释你的问题。
