### ISSUE TITLE
导出mhtml必须勾选html

### ISSUE THREAD

**Issue by hype1type** [qiye45/wechatDownload#194]
**描述该错误**
对该错误的简明扼要的描述。

单独无法导出mhtml，必须一同勾选HTML才能批量导出

**链接和截图**
添加链接和截图以帮助解释你的问题。
https://mp.weixin.qq.com/s/F6nXW2pD6MPwz2xhtzhkVQ
无
**其他信息**
在这里添加关于该问题的任何其他背景。

无

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/42

**Comment by hype1type** [comment]
> #42

还请在页面标注一下，告诉新用户

**Comment by qiye45** [comment]
下个版本我加一下吧

**Comment by qiye45** [comment]
3.3加上啦
