### ISSUE TITLE
会一直下载吗？不停止吗

### ISSUE THREAD

**Issue by hype1type** [qiye45/wechatDownload#195]
描述该错误
对该错误的简明扼要的描述。
不知道何时停止，一直显示下面的东西

链接和截图
添加链接和截图以帮助解释你的问题。
![image](https://github.com/user-attachments/assets/059b7085-f122-4526-a292-8982ba64928c)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
应该是下载完了，关掉软件就好了
