### ISSUE TITLE
3.2版本一直提示刷新接口等待，一直等待

### ISSUE THREAD

**Issue by kyler009** [qiye45/wechatDownload#196]
描述该错误
对该错误的简明扼要的描述。

链接和截图
添加链接和截图以帮助解释你的问题。

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/195

**Comment by kyler009** [comment]
目前获取秘钥是不是提示失败，即使成功后也一直暂停访问公众号，一直在暂停
