### ISSUE TITLE
可以手动停止吗？

### ISSUE THREAD

**Issue by zdnyp** [qiye45/wechatDownload#197]
我使用了默认的起止时间，现在想中断，怎么停止呢？直接关闭吗？

谢谢。

**Comment by zdnyp** [comment]
突然改变想法，不想继续下载了，想要停止。

**Comment by zdnyp** [comment]
我尝试了直接停止，好像是可行的，建议增加一个停止的按钮功能：）

**Comment by qiye45** [comment]
试试关掉软件

**Comment by leeyis** [comment]
> 我尝试了直接停止，好像是可行的，建议增加一个停止的按钮功能：）

我也想提这个需求

**Comment by qiye45** [comment]
我看看吧

**Comment by qiye45** [comment]
3.4更新暂停功能啦
![image](https://github.com/user-attachments/assets/ef5c4ec0-a216-4da8-b27e-0093f1d77e37)
![image](https://github.com/user-attachments/assets/2026a9b6-ab31-4e05-90fa-185b3bbed845)
![image](https://github.com/user-attachments/assets/d524b91e-7815-474e-9a6e-bdcaa62ee48b)
