### ISSUE TITLE
可以下载单篇文章，但是没法获取id

### ISSUE THREAD

**Issue by fox-404** [qiye45/wechatDownload#198]
**描述该错误**
在微信打开后无法获取id，Windows更新后无法使用，之前正常下载

**链接和截图**
![image](https://github.com/user-attachments/assets/b2b644a7-093f-4796-9dd5-bbd0aec44082)

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
用新版本

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/releases/tag/3.2

**Comment by BKDragon** [comment]
新版本求个 MacOS 版。

> https://github.com/qiye45/wechatDownload/releases/tag/3.2

**Comment by qiye45** [comment]
> MacOS

macos后面应该会更新，关注一下群消息咯 https://t.me/changfengbox
