### ISSUE TITLE
3.1版本的“依然”从“获取公众号ID”这第一步就把路给堵死了

### ISSUE THREAD

**Issue by LeonNadal** [qiye45/wechatDownload#199]
获取公众号历史消息页面成功，请在微信打开复制的链接：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz + "&scene=124#wechat_redirect

文章地址：https://mp.weixin.qq.com/s/khkHVsGE45SY8CMC2dwrYQ

![image](https://github.com/user-attachments/assets/e667e8e8-3574-4716-acc5-0ac8280715f0)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/releases/tag/3.2
