### ISSUE TITLE
点击获取ID后自动退出

### ISSUE THREAD

**Issue by Chuanyu-Li** [qiye45/wechatDownload#2]
点击获取ID后自动退出

**Comment by qiye45** [comment]
可能是微信文章链接的问题，发一下链接吧

**Comment by Chuanyu-Li** [comment]
你好，我按自己的思路写了一下代码，已经获取到数据了。当时文章链接是https://mp.weixin.qq.com/s?__biz=MzA3MjA1MjMxNw==&mid=2651591870&idx=1&sn=1a03b2622ac3ccd08283d180ae3c71c7&chksm=84dc8f8cb3ab069a289a386d610f787f497ea60f6d95bbbfbab02a4a5d91bf39a1310d1bdcf1#rd

**Comment by midpoint** [comment]
微信设置里面不要设置为用默认浏览器打开链接
