### ISSUE TITLE
2.2版本使用过程中的几个问题

### ISSUE THREAD

**Issue by LouisLen** [qiye45/wechatDownload#20]
1.获取公众号ID过程中提示“获取秘钥失败...请先在微信打开复制的链接”；
2.导出PDF没反应；
3.导出评论失败；
4.下载评论回复复选框无法勾选。
以上，祝作者龙年大吉！

**Comment by qiye45** [comment]
打开软件里面有一个视频教程，跟着教程试一试

**Comment by LouisLen** [comment]
> 打开软件里面有一个视频教程，跟着教程试一试

已经按着教程操作过了，目前还是无法获取到公众号ID

**Comment by qiye45** [comment]
看看这个issue https://github.com/qiye45/wechatDownload/issues/9

**Comment by qiye45** [comment]
或者加群看看咯 https://t.me/changfengbox

**Comment by lvbest** [comment]
显示操作频繁，获取密钥成功后点批量下载没反应

**Comment by lvbest** [comment]
> > 显示操作频繁，获取密钥成功后点批量下载没反应
> 
> 可能是下载太多，被微信限制了

怎么才能恢复呢

**Comment by lvbest** [comment]
> > 显示操作频繁，获取密钥成功后点批量下载没反应
> 
> 可能是下载太多，被微信限制了

这个情况怎么能恢复呢？

**Comment by qiye45** [comment]
> > > 显示操作频繁，获取密钥成功后点批量下载没反应
> > 
> > 
> > 可能是下载太多，被微信限制了
> 
> 这个情况怎么能恢复呢？

等一天或者换个微信

**Comment by ileeweicn** [comment]
我一开始也是不显示获得密钥，然后呢，我就挂机，把两个窗口放那里没管。去扔了个垃圾回来。嘿嘿，就获取了，所以耐心等一等吧。
