### ISSUE TITLE
批量下载显示在下载，实际下载文件夹没有生成东西；或者就是不断的显示暂停下载

### ISSUE THREAD

**Issue by aass0810** [qiye45/wechatDownload#200]
![微信图片_20240922193548](https://github.com/user-attachments/assets/bdec7d8c-501e-4a0e-8d51-0f9c159e7bb5)

**Comment by qiye45** [comment]
自定义时间的起始时间填错了
![image](https://github.com/user-attachments/assets/173e4b40-4ff8-42b4-b8fc-f956b86be5b2)
