### ISSUE TITLE
3.2最新版本获取秘钥成功后点击下载下方一直提示防止访问公众号被限制，多少秒。。。

### ISSUE THREAD

**Issue by kyler009** [qiye45/wechatDownload#202]
描述该错误
对该错误的简明扼要的描述。
3.2最新版本获取秘钥成功后点击下载下方一直提示防止访问公众号被限制，多少秒。。。
![暂停](https://github.com/user-attachments/assets/800316a4-ea6f-4e30-b50f-05b00fa06409)
实际没有下载成功，没有生成下载文件夹

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/201

**Comment by kyler009** [comment]
单篇能下载下来，但是提示评论回复下载失败
