### ISSUE TITLE
无法下载付费文章

### ISSUE THREAD

**Issue by simuleite** [qiye45/wechatDownload#206]
已经付费的文章，下载下来只有试读部分。
下载内容：
![图片](https://github.com/user-attachments/assets/6c290e84-c9f5-4166-9f41-9dd5a8f8c521)
文章内容：
![图片](https://github.com/user-attachments/assets/675c8c7e-0467-4a13-a8fb-dbafe467140c)

**Comment by qiye45** [comment]
试试批量下载可以吗

**Comment by mitlearn** [comment]
> 试试批量下载可以吗

不可用 仅能下载到付费墙前
![image](https://github.com/user-attachments/assets/db45d4e2-aa47-4bc6-99d5-461ba506868b)
