### ISSUE TITLE
由临时目录引起的火绒「联网控制」许可弹窗？

### ISSUE THREAD

**Issue by Sunsh4j** [qiye45/wechatDownload#207]
每次打开软件，火绒都会弹窗联网提醒（比较麻烦），所以每次我都选择了记住选择，但是毫不管用
![image](https://github.com/user-attachments/assets/b68be511-552c-40f7-b580-37de391ae235)

我又去火绒的联网设置里，输入软件的全路径，然后选择「自动允许」，还是不管用

最后，我发现每次双击打开的软件是在最开始下载保存软件的路径，但是实际打开的是一个临时目录下的exe文件？？
![image](https://github.com/user-attachments/assets/7f4b2929-3aa0-4216-9422-4580370a416f)

另外，之前一直用着2.4版本，现在用着3.x版本，打开软件后直接输入文章链接就可以下载，所以现在是可以不用先获取公众号id，就可以直接下载文章了吗？

**Comment by qiye45** [comment]
火绒的联网控制关一下咯

**Comment by qiye45** [comment]
用单篇下载，不用获取公众号id的，批量下载才需要
