### ISSUE TITLE
无法下载，一直暂停多少秒状态，

### ISSUE THREAD

**Issue by kyler009** [qiye45/wechatDownload#208]
看图可以看到，获取秘钥成功后，直接是暂停多少秒，实际无法下载，后面一直显示一直暂停多少秒状态

![无法下载](https://github.com/user-attachments/assets/25d7ac8c-88f2-472a-b43d-6b2b309b9fa1)

之前提过这个问题，但是不知道其他人遇到么，
![微信](https://github.com/user-attachments/assets/6267911c-73b7-421a-ada7-76a58bdc4e5d)
![xit ](https://github.com/user-attachments/assets/a4e09a30-2589-4dca-af4b-7b20ba39606f)

微信版本及系统版本截图如上

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/201

**Comment by kyler009** [comment]
> #201

老铁，你测试的都正常吗

**Comment by qiye45** [comment]
看看开始下载页数
![image](https://github.com/user-attachments/assets/f2ac4aa4-0cee-4dd4-a7f7-6f6c197ea590)

**Comment by kyler009** [comment]
> 看看开始下载页数 ![image](https://private-user-images.githubusercontent.com/138199658/373737279-f2ac4aa4-0cee-4dd4-a7f7-6f6c197ea590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODg0MTYsIm5iZiI6MTcyODA4ODExNiwicGF0aCI6Ii8xMzgxOTk2NTgvMzczNzM3Mjc5LWYyYWM0YWE0LTBjZWUtNGRkNC1hN2Y3LTZmNmMxOTdlYTU5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMDI4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzgwNDYzOGI2YzY2ZDYxMTQ1NzY1MGEwZWJhNjc4OWQyMmY0YmI4NDg1OThkZjRiNGVjY2MxM2YwZDZkZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tXWyX-Tp0dBqy6MaWB16Iw79Jj2tAcTJcTXEFm15zD0)

我是选择了最新的一篇微信文章，开始批量下载后后提示这个，下载页数不知道该怎么修改

**Comment by qiye45** [comment]
![image](https://github.com/user-attachments/assets/5c10c5ec-c4bb-4bba-a515-5e624ec7dbf0)

**Comment by kyler009** [comment]
> 把缓存文件夹里面的setting删了，或者下载页数调成大于0
> 
> ![image](https://private-user-images.githubusercontent.com/138199658/373837760-335262c7-8897-40a7-9aac-8979854c9a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDk1MzMsIm5iZiI6MTcyODEwOTIzMywicGF0aCI6Ii8xMzgxOTk2NTgvMzczODM3NzYwLTMzNTI2MmM3LTg4OTctNDBhNy05YWFjLTg5Nzk4NTRjOWE0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwNjIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDliNWNkZGYzMmM2YjNjMjZiNjgxMTU5ZjQ0MzYxMzY5MDYxZGFlZDIyNDk1OGMxYTkzYjdjZWFhYjNhYjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QyztRj1gidOboG-W--RY8WixYB874ukcjtYMiz9J25Y) ![image](https://private-user-images.githubusercontent.com/138199658/373837679-5c10c5ec-c4bb-4bba-a515-5e624ec7dbf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDk1MzMsIm5iZiI6MTcyODEwOTIzMywicGF0aCI6Ii8xMzgxOTk2NTgvMzczODM3Njc5LTVjMTBjNWVjLWM0YmItNGJiYS1hNTE1LTVlNjI0ZWM3ZGJmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwNjIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2E5YjYyZTg3MGY4OTFlZTU0MjA4YWVlNTQ4MjQ0ZGQxNGI1MjNkZTcyZjAzYTVmNDUyM2UwMGQ2ZTYzNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tfemlYShftmNiVdhGBpE5e94B-3ERQvahpzZMPVFckE)

完美解决，谢谢老铁！！

**Comment by wplong0905** [comment]
这个最多就是下载500条么？可以更多么？

**Comment by qiye45** [comment]
下载太多会触发微信风控了 https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416

**Comment by zany312** [comment]
这个是触发微信风控了~
晚点再搞
