### ISSUE TITLE
3.2 无法批量导出 下载完成后无法结束扫描下载

### ISSUE THREAD

**Issue by E-one-LLC** [qiye45/wechatDownload#209]
描述该错误
**在勾选 “导出PDF”、“文件开头添加日期”、 “选择时间：全部”的情况下 无法批量导出  仅生成封面**

**批量下载完成后，无法停止扫描** 

链接和截图
下面为 下载完成后，一直扫描的截图
![批量下载完成后，不停止扫描01](https://github.com/user-attachments/assets/f02d630c-e48f-4ea0-9110-b5e0d210b7ea)

![批量下载完成后，不停止扫描02](https://github.com/user-attachments/assets/ac88f56f-a27f-4088-8997-e0f0ce02c1a0)

其他信息

1、程序目录 里的 “下载”  能生成以提供链接的“公众号”名称的文件夹

2、无法批量导出时，程序显示 正在下载，但是公众号文件夹里生成的是 封面 

错误分析
怀疑无法导出 是没有把**缓存**文件夹和**微信公众号文章批量下载工具3.2** 放在一起

下图为仅勾选 **导出PDF**、**文件开头添加日期**、**选择时间：全部**  
只有**微信公众号文章批量下载工具3.2**  导出的封面
![image](https://github.com/user-attachments/assets/94e8977a-86ac-4cbe-8005-0a07754551b9)

不知道我的描述 您是否能看明白。。

**Comment by qiye45** [comment]
可能下载太多触发微信风控了
https://github.com/qiye45/wechatDownload/issues/208#issue-2563484398

**Comment by E-one-LLC** [comment]
> 可能下载太多触发微信风控了 [#208 (comment)](https://github.com/qiye45/wechatDownload/issues/208#issue-2563484398)

所以单独勾选PDF 也是可以的 对吧？

**Comment by E-one-LLC** [comment]
> 可能下载太多触发微信风控了 [#208 (comment)](https://github.com/qiye45/wechatDownload/issues/208#issue-2563484398)

确实一次 下载了151篇。。挺多的。。

**Comment by E-one-LLC** [comment]
> 可能下载太多触发微信风控了 [#208 (comment)](https://github.com/qiye45/wechatDownload/issues/208#issue-2563484398)

看了https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416) 的回复
应该是要 把 **导出HTML** 当做必选项。 然后在选择 **导出pdf**才会生效 。

**Comment by qiye45** [comment]
> > 可能下载太多触发微信风控了 [#208 (comment)](https://github.com/qiye45/wechatDownload/issues/208#issue-2563484398)
> 
> 看了[#9 (comment)](https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416)) 的回复 应该是要 把 **导出HTML文件** 当做必选项。 然后在选择 **导出pdf**才会生效 。

对

**Comment by E-one-LLC** [comment]
> > > 可能下载太多触发微信风控了 [#208 (comment)](https://github.com/qiye45/wechatDownload/issues/208#issue-2563484398)
> > 
> > 
> > 看了[#9 (comment)](https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416)) 的回复 应该是要 把 **导出HTML文件** 当做必选项。 然后在选择 **导出pdf**才会生效 。
> 
> 对

了解了，
看来 您可以把html设置成 必选项
 嘻嘻
 问题解决了 我先关闭了
