### ISSUE TITLE
Windows3.2版本还是存在获取秘钥失败问题

### ISSUE THREAD

**Issue by Midsummerlc** [qiye45/wechatDownload#210]
**描述该错误**
Windows3.2版本还是存在获取秘钥失败问题
**链接和截图**
![image](https://github.com/user-attachments/assets/d818d064-2378-4667-8aa4-fd83adb31260)

**Comment by qiye45** [comment]
试试这个 https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416

**Comment by Midsummerlc** [comment]
辛苦大佬。

似乎确实是Windows版本问题，win10版本号22H2的版本就会获取秘钥失败，看到评论区也有别人跟我一样。



***@***.***
 
发件人： qiye45
发送时间： 2024-10-11 18:21
收件人： qiye45/wechatDownload
抄送： Midsummerlc; Author
主题： Re: [qiye45/wechatDownload] Windows3.2版本还是存在获取秘钥失败问题 (Issue #210)
试试这个 #9 (comment)
