### ISSUE TITLE
希望 能在文件开头添加日期后 增加一个空格 

### ISSUE THREAD

**Issue by E-one-LLC** [qiye45/wechatDownload#213]
**描述你想要的功能**

希望 能在文件开头添加日期后 增加一个空格 

如图 遇到文件名数字在前面的  按时间排序就会出现问题

![image](https://github.com/user-attachments/assets/c273ae6d-d3b9-41fc-920f-bd1e32896a0b)

**Comment by qiye45** [comment]
写一个脚本

**Comment by E-one-LLC** [comment]
> 写一份脚本

我不会，，还望大佬出手

**Comment by qiye45** [comment]
(＃°Д°)

**Comment by anlish01** [comment]
批量重命名软件很多，自己去找一下，比如：https://www.binfensoft.cn/

**Comment by E-one-LLC** [comment]
> 批量重命名软件很多，自己去找一下，比如：https://www.binfensoft.cn/

谢谢 兄弟 

> (＃°Д°)

哈哈哈哈 我还以为 大佬直接优化。。
