### ISSUE TITLE
使用3.2在win10电脑批量下载的时候出现下列

### ISSUE THREAD

**Issue by Sparkgrey** [qiye45/wechatDownload#214]
点击批量下载后，一直提示防止访问公众号被限制，暂停XX秒；并且需要下载内容的发布时间也不对
![image](https://github.com/user-attachments/assets/59d84eb6-858d-453a-8d57-9a5e871f2688)

**Comment by qiye45** [comment]
改一下 开始下载页数

**Comment by kyler009** [comment]
> 改一下 开始下载页数

老铁，还一个问题，现在下载评论回复是失败的

**Comment by IceCola** [comment]
@qiye45 现在评论下载一直是失败的，不知道为啥

**Comment by qiye45** [comment]
试试批量下载的

**Comment by kyler009** [comment]
> 试试批量下载的

批量下载也失败了

**Comment by Sparkgrey** [comment]
> 改一下 开始下载页数

应该改为多少？我试了下如果是一个新的微信号，那就可以下一部分（比如某个公众号我想下载过去2年的文章，可能下到一年~一年半的文章是可以成功的），但是最新的半年就下不了了，会出现我截图的问题；
隔天用同样的微信号测试，把下载页数改为200/150，还是如截图一样的问题，下载不下来。
另外，确实之前即便下载成功的那一部分，评论也下载失败

**Comment by Sparkgrey** [comment]
> 改一下 开始下载页数

应该改为多少？我试了下如果是一个新的微信号，那就可以下一部分（比如某个公众号我想下载过去2年的文章，可能下到一年~一年半的文章是可以成功的），但是最新的半年就下不了了，会出现我截图的问题；
隔天用同样的微信号测试，把下载页数改为200/150，还是如截图一样的问题，下载不下来。
另外，确实之前即便下载成功的那一部分，评论也下载失败

**Comment by kyler009** [comment]
> > 改一下 开始下载页数
> 
> 应该改为多少？我试了下如果是一个新的微信号，那就可以下一部分（比如某个公众号我想下载过去2年的文章，可能下到一年~一年半的文章是可以成功的），但是最新的半年就下不了了，会出现我截图的问题； 隔天用同样的微信号测试，把下载页数改为200/150，还是如截图一样的问题，下载不下来。 另外，确实之前即便下载成功的那一部分，评论也下载失败

之前老铁说过，你把软件包缓存文件夹setting删掉，重新打开软件能解决这个下载页数的问题，但是评论下载失败这个我还没解决

**Comment by qiye45** [comment]
评论下载失败，发一下文章链接吧

**Comment by Sparkgrey** [comment]
> > > 改一下 开始下载页数
> > 
> > 
> > 应该改为多少？我试了下如果是一个新的微信号，那就可以下一部分（比如某个公众号我想下载过去2年的文章，可能下到一年~一年半的文章是可以成功的），但是最新的半年就下不了了，会出现我截图的问题； 隔天用同样的微信号测试，把下载页数改为200/150，还是如截图一样的问题，下载不下来。 另外，确实之前即便下载成功的那一部分，评论也下载失败
> 
> 之前老铁说过，你把软件包缓存文件夹setting删掉，重新打开软件能解决这个下载页数的问题，但是评论下载失败这个我还没解决
我这里试了下不行。。  我后面有试过把下载页数改小，比如90,80,70,60......每次改小一些都能再成功下载一些下来（评论是肯定下载不了的），但是下载了10几篇以后就又出现我开头的问题了，不停提示我“防止XXX, 暂停XX秒”；
然后我尝试把下载页数重新改大，怎么改都没用，必须不停改小好像才会有点用，但是到最后小到0就小不下去了呀

**Comment by Sparkgrey** [comment]
> > > 改一下 开始下载页数
> > 
> > 
> > 应该改为多少？我试了下如果是一个新的微信号，那就可以下一部分（比如某个公众号我想下载过去2年的文章，可能下到一年~一年半的文章是可以成功的），但是最新的半年就下不了了，会出现我截图的问题； 隔天用同样的微信号测试，把下载页数改为200/150，还是如截图一样的问题，下载不下来。 另外，确实之前即便下载成功的那一部分，评论也下载失败
> 
> 之前老铁说过，你把软件包缓存文件夹setting删掉，重新打开软件能解决这个下载页数的问题，但是评论下载失败这个我还没解决

我试过了没用。
之前我有试过把下载页数改小，比如90,80,70,60.....这样慢慢改小，每次都又能下载成功一些文章下来（评论一直是下载失败的）。。。
_实际效果类似于我想下载比如最近3个月的一共90篇文章，我把下载页数改为80，然后点击批量下载，能下成功个15篇文章，然后就出现一开始的错误，我就把下载页数再改小一点改到70，再点批量下载，就又能下成功个10篇文章，这样一直循环。。但是改到后面再小也改不下去了，我想下的文章也没下完。_
但是如果我把页数重新改大，就完全没用，比如从70重新改为80，就一点都下不下来，一直出现原图里“防止XXX, 暂停XX秒”的问题

**Comment by qiye45** [comment]
应该微信改了啥，等我看看

**Comment by qiye45** [comment]
评论下载失败的问题，3.3新版本修复啦

[科技爱好者周刊322内容行业的内幕.pdf](https://github.com/user-attachments/files/17590331/322.pdf)

**Comment by white0dew** [comment]
> 评论下载失败的问题，3.3新版本修复啦
> 
> [科技爱好者周刊322内容行业的内幕.pdf](https://github.com/user-attachments/files/17590331/322.pdf)

大佬。在下载链接里没有看到3.3的版本哦

**Comment by white0dew** [comment]
现在导出表格的时候还是没有评论的数量;
![image](https://github.com/user-attachments/assets/3fb996e2-61cf-477e-b381-51d409777ce2)

**Comment by qiye45** [comment]
等新版本吧

**Comment by qiye45** [comment]
新版本已更新
