### ISSUE TITLE
openssl报错

### ISSUE THREAD

**Issue by boxertan** [qiye45/wechatDownload#215]
**描述该错误**
无法打开

**链接和截图**

![image](https://github.com/user-attachments/assets/92f4a7a0-cbfd-44e1-89ab-b595e7909b0b)

**其他信息**
win11

**Comment by qiye45** [comment]
换台电脑试试

**Comment by boxertan** [comment]
> 换台电脑试试

换了一台电脑就好了，这是为啥？？

**Comment by qiye45** [comment]
电脑缺openssl的依赖，是精简版吗🤔

**Comment by boxertan** [comment]
> 电脑缺openssl的依赖，是精简版吗🤔

不是精简版吧？？？

版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎10/‎16
操作系统版本	22000.376
体验	Windows 功能体验包 1000.22000.376.0
