### ISSUE TITLE
这种自身电脑出的问题该如何解决

### ISSUE THREAD

**Issue by aha667** [qiye45/wechatDownload#219]
描述该错误：这是缓存出问题了吗？
我选择10月14到25的日期后，它输出的是以前爬过的，而且文章没有下载下来，一直都是防止访问公众号被限制，暂停4秒

链接和截图：
![sp20241025_090723_253](https://github.com/user-attachments/assets/4bd64229-1ff3-420a-b73a-6e8209b84e9f)

**Comment by qiye45** [comment]
因为会保存下次的下载进度，到缓存文件夹把setting删了

**Comment by qiye45** [comment]
或者换台电脑试试
