### ISSUE TITLE
md格式结尾会带一些无关信息，可以去掉吗

### ISSUE THREAD

**Issue by tcmtom** [qiye45/wechatDownload#22]
![image](https://github.com/qiye45/wechatDownload/assets/94541098/d8b161f7-74b5-46de-a309-547f3678825e)

md格式的下载下来末尾会带着这些东西可以去掉吗

**Comment by qiye45** [comment]
下个版本我优化一下，可以用文本编辑器批量去除一下

**Comment by qiye45** [comment]
2.3版本下载md会去掉这些信息啦
