### ISSUE TITLE
导出表格功能生成的csv里长标题被截断

### ISSUE THREAD

**Issue by e20999** [qiye45/wechatDownload#220]
生成的csv文件里标题只能是限定个数字符，多余部分被截断了，标题内的标点符号也被过滤掉了，标题内容不完整且不好理解标题意思。实际需要完整的原格式原内容长标题。
导出表格功能，另是否可以增加封面图片链接网址，方便批量下载封面图片。
谢谢。

如原标题：透视职场真相1668｜发现并克服掉自身的一些弱点，逼自己养成一些好习惯，你慢慢也就变强大且不会那么在意自己所处的境遇了
导出表格功能生成的csv文件里标题：透视职场真相1668发现并克服掉自身的一些弱点逼自己养成一些好习惯你慢慢也就变强大且不会那么在

**Comment by qiye45** [comment]
文件名一般不能有标点符号，表格的问题等我修一下吧

**Comment by qiye45** [comment]
3.3修复啦

**Comment by qiye45** [comment]
会保存原标题
![image](https://github.com/user-attachments/assets/2b0edb9f-ee3e-4b6b-a819-7f0ec5218818)

**Comment by e20999** [comment]
> 会保存原标题 ![image](https://private-user-images.githubusercontent.com/138199658/383458881-2b0edb9f-ee3e-4b6b-a819-7f0ec5218818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDIwNTksIm5iZiI6MTczMTE0MTc1OSwicGF0aCI6Ii8xMzgxOTk2NTgvMzgzNDU4ODgxLTJiMGVkYjlmLWVlM2UtNGI2Yi1hODE5LTdmMGVjNTIxODgxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzM5ZDZiZDk0MjBjZWFmNzY0OTg2YjNlNjk0MWQ4MjAxMjI5M2RiMGQ0ZmEwNzkwZDdhYTMwNjg1NTJkMDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qaH4GHkfaYCx2LzpPkNDqEOqKXg09k1l-3KJT6wtZF8)

您最帅，您最快！
