### ISSUE TITLE
评论下载失败

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#221]
3.2版本，批量下载时，一直提示【评论下载失败】
是文章本身就没有评论？还是软件的bug？

公众号：参考以下链接
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MjM5MjUwMjQzNw==&scene=124#wechat_redirect

![image](https://github.com/user-attachments/assets/3eb79f9d-c46b-471f-9598-e53ce829fd23)

**Comment by qiye45** [comment]
等3.3新版本吧，微信改了啥

**Comment by qiye45** [comment]
3.3修复啦

**Comment by qiye45** [comment]
等一下，马上
![image](https://github.com/user-attachments/assets/0743be79-d1d0-4b00-944c-2539345204f3)

**Comment by hrbagang** [comment]
V3.3最新版，批量下载时，还是提示 评论下载失败。。。
微信文章链接：https://mp.weixin.qq.com/s/WuvWJ8Tsj0HCskCmi8GGjg

![image](https://github.com/user-attachments/assets/e1c718f0-b802-463b-9d70-1316e3ef693b)

**Comment by qiye45** [comment]
公众号本身没评论
![image](https://github.com/user-attachments/assets/2c3bade3-ece8-4653-b2e4-3f16656d8c9f)

**Comment by hrbagang** [comment]
本身没有评论的文章，下载时的提示报错信息，希望能修改一下。例如：不显示报错信息，或者是显示文章没有评论。
