### ISSUE TITLE
V3.3 批量下载失败

### ISSUE THREAD

**Issue by SilenceWinter** [qiye45/wechatDownload#225]
描述该错误
1. 批量下载不管选什么时间范围还是自定义时间范围，任何文章都不能下载

链接和截图
截图中显示的文章，实际一篇都没有下载
图片如下：

<img width="716" alt="无标题" src="https://github.com/user-attachments/assets/8ed12625-0395-42a8-b8ff-17e2a8657c21">

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
检查一下 https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416
