### ISSUE TITLE
【新功能建议】增加选项：密钥获取成功后自动开始批量下载文章

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#227]
希望能增加一个选项：
就是在密钥获取成功后，
      自动开始批量下载文章
的这样一个选项。

现在每次都是获取密钥成功后，再手动点一下 批量下载文章 的按钮。

因为从显示
       开始获取秘钥...
到
       获取秘钥成功！请点击下载按钮
之间还要等一段时间。。。

**Comment by qiye45** [comment]
问题不大，点一下的事(＃°Д°)
