### ISSUE TITLE
同一个公众号会生成2个下载目录

### ISSUE THREAD

**Issue by xurdy** [qiye45/wechatDownload#228]
**描述该错误**
如图我下载一个名为“图溯上海”公众号的文章但是会生成2个下载文件夹，这是正常现象？还是只有我一个人这样？
![PixPin_2024-11-08_22-37-53](https://github.com/user-attachments/assets/5e4c1d07-03a1-442e-90d4-c5d2e3a0d760)

**链接和截图**
添加链接和截图以帮助解释你的问题。

**其他信息**
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
获取不到公众号名称的时候，会放公众号文件夹

**Comment by xurdy** [comment]
> 获取不到公众号名称的时候，会放公众号文件夹

原来如此
