### ISSUE TITLE
获取不到密钥了 ,如何解决啊 ?

### ISSUE THREAD

**Issue by chxgzs** [qiye45/wechatDownload#229]
描述该错误
对该错误的简明扼要的描述。

链接和截图
添加链接和截图以帮助解释你的问题。
![image](https://github.com/user-attachments/assets/a9bc584b-f7c9-4354-bd55-b6f9b1ba34b4)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
试试最新版
