### ISSUE TITLE
阅读量这些数据拿到的都是0，不是准确的数据

### ISSUE THREAD

**Issue by xiangt2** [qiye45/wechatDownload#231]
描述该错误
对该错误的简明扼要的描述。

链接和截图
添加链接和截图以帮助解释你的问题。

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
应该微信改了啥，下个版本我修一下

**Comment by tinybye** [comment]
导出表格时，3.2可以获取阅读量，但是标题的标点都没有了，3.3标题正常，但是阅读量获取不到

**Comment by qiye45** [comment]
3.4修复获取阅读量失败的问题啦
[2024-12-07-222929.csv](https://github.com/user-attachments/files/18048738/2024-12-07-222929.csv)
