### ISSUE TITLE
获取公众号id失败

### ISSUE THREAD

**Issue by ai668chen** [qiye45/wechatDownload#237]
描述该错误
第一次运行时可以获取到id，并且正常下载。但是由于时间期限没有选对，导致下载公众号下全部内容，一直在下载，没有找到停止运行按钮，所以强制关闭了程序，再次打开使用后，就一直无法获取公众号id，如何解决？
下载单篇文章，提示下载成功，打开下载目录，没有文件。
重启微信，重启电脑都没有解决。

链接和截图
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIzMzc4NTg5OQ==&scene=124#wechat_redirect
![2024-11-20 22 55 39](https://github.com/user-attachments/assets/070b3bda-c15e-4ce8-9391-6ed3dfe6ee11)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
把梯子关了试试，应该网络问题
