### ISSUE TITLE
获取不到评论

### ISSUE THREAD

**Issue by aaaazzzx** [qiye45/wechatDownload#238]
描述该错误
对该错误的简明扼要的描述。
获取不到评论，提示评论下载失败
链接和截图
添加链接和截图以帮助解释你的问题。
https://mp.weixin.qq.com/s/Yj5iSXWLRHMpS_qV5KnAJw
其他信息
在这里添加关于该问题的任何其他背景。
可以正常导出正文

**Comment by aaaazzzx** [comment]
3.3

**Comment by qiye45** [comment]
用批量下载的
