### ISSUE TITLE
【V3.3】批量下载时，总是自己停止

### ISSUE THREAD

**Issue by hrbagang** [qiye45/wechatDownload#239]
**描述该错误**
【V3.3】批量下载时，中途总是自己停止。需要关闭APP后再次打开，重新操作才能继续下载。
下载过的公众号，只要文章数量稍微多一些，都有这个问题。
是秘钥有期限，过期了的原因吗？

**链接和截图**
公众号文章链接：https://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5MjgwNjgwMA==&appmsgid=10000340&itemidx=2&sign=4acc122a327bdcefb6ba3d1c8106e9c0&scene=27&poc_token=HPaiPmejagJzb2qm_S7NReAATcwGTXpJ5P466XK6

截图：
开始下载时
![IMG_20241121_124758](https://github.com/user-attachments/assets/9912fb26-d3fd-48fe-8952-595662270c4b)

中途中断（不再下载，不再出新的log）
![IMG_20241121_124912](https://github.com/user-attachments/assets/eec4a156-02a7-4be6-86da-ea46cf9b0ec9)

关闭APP后再次打开，重新操作才能继续下载
![IMG_20241121_125841](https://github.com/user-attachments/assets/62671e0d-50eb-47d4-abeb-599048072933)

**Comment by qiye45** [comment]
是秘钥是有期限的，重新获取秘钥咯
