### ISSUE TITLE
你好，能否增加下载公众号内的视频、音频、封面图这些信息？已经导出公众号文章链接的功能。

### ISSUE THREAD

**Issue by zixun123** [qiye45/wechatDownload#24]
你好，能否增加下载公众号内的视频、音频、封面图这些信息？已经导出公众号文章链接的功能。

**Comment by qiye45** [comment]
下个版本吧

**Comment by UntaggedRui** [comment]
感谢开发者，我也想要这个功能。把资源全部保存在本地，防止文章被和谐后这些引用的资源例如图片无法访问。

**Comment by qiye45** [comment]
> 感谢开发者，我也想要这个功能。把资源全部保存在本地，防止文章被和谐后这些引用的资源例如图片无法访问。

这个挺麻烦的，可能要后面的版本啦
现在图片可以离线保存哒

**Comment by qiye45** [comment]
2.4 支持下载视频、音频、封面图啦

**Comment by UntaggedRui** [comment]
> 2.4 支持下载视频、音频、封面图啦
> 
> ![image](https://private-user-images.githubusercontent.com/138199658/324252381-5e277c6c-704e-4000-bdbd-55e3086fe95b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDkxNDcsIm5iZiI6MTcxMzcwODg0NywicGF0aCI6Ii8xMzgxOTk2NTgvMzI0MjUyMzgxLTVlMjc3YzZjLTcwNGUtNDAwMC1iZGJkLTU1ZTMwODZmZTk1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNDE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjY1Mzg1YmUwOWQ0ZjBjZTM0ZmNlY2FmY2FmNTI2YjQ2OTAzMjkwYjZjNjI5MWIwYTQwMTMzN2JlNzk1YmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RFbKmiVB95Lf3e1mIi5UovNPzmDx72gnqvo9kEo0c08)

2.4版本是还没发布吗，release中没有看到
