### ISSUE TITLE
提示“网络错误，连接不到服务器”。没连梯子

### ISSUE THREAD

**Issue by soha0219** [qiye45/wechatDownload#244]
![图片1](https://github.com/user-attachments/assets/141bcc48-4423-4240-88a9-ba978af56175)

**Comment by FCJ-1106** [comment]
卧槽，我也遇到了，前两天还能用来着

**Comment by wanghb2024** [comment]
前天可以用，昨天就不能用了

**Comment by liwenjie160** [comment]
![image](https://github.com/user-attachments/assets/b9f74105-f7df-46cc-b1fb-b61fe2608214)
同不能用，也是一样的提示，没开梯子

**Comment by PuningZhadougan** [comment]
我也不行诶 你们现在还可以用吗

**Comment by h9052300** [comment]
我也发生相同的状况~

**Comment by iceblue0227** [comment]
好了没两天，又开始了

**Comment by qiye45** [comment]
服务器挂了，下载好啦
