### ISSUE TITLE
显示提示：网络错误，无法连接到服务器

### ISSUE THREAD

**Issue by PuningZhadougan** [qiye45/wechatDownload#245]
描述该错误
显示提示：网络错误，无法连接到服务器

链接和截图
![image](https://github.com/user-attachments/assets/02c4653e-615e-4f2a-94ba-e75b55cb61ac)

其他信息
目前使用win11笔记本 文件存放在非C盘 专用网络 国内无使用梯子 但就是反复尝试无法使用 请求帮助TAT

**Comment by zjqc** [comment]
遇到了同样的问题

**Comment by qiye45** [comment]
服务器挂了，下载好啦

**Comment by zjqc** [comment]
it seems that it is available now

**Comment by qiye45** [comment]
Yeah, the server's been upgraded.
