### ISSUE TITLE
点击下载没反应

### ISSUE THREAD

**Issue by litchemine** [qiye45/wechatDownload#248]
1、能够获取Id和私钥
2、点击“导出表格”，能显示“起始下载页数”信息，但是不下载

![image](https://github.com/user-attachments/assets/d867d4d0-2cfd-48c6-b105-3b2f05be8d29)

原因猜测：
在此之前，大概下载了20分钟左右，然后微信内置浏览器就不能访问了
输入获取秘钥的链接，显示“操作频繁，请稍后再试”

![image](https://github.com/user-attachments/assets/2528c35c-474f-4ab3-a1f9-56589a02eefc)

**Comment by qiye45** [comment]
看看这个 https://github.com/qiye45/wechatDownload/issues/9
