### ISSUE TITLE
建议：1.增加可下载任意网页； 2.增加可导出文章（或表格数据等）导出为excle ;

### ISSUE THREAD

**Issue by Wiliiiam1949** [qiye45/wechatDownload#25]

**Comment by Wiliiiam1949** [comment]
下载文章一起出现 获取 密钥失败 
<img width="549" alt="2024-02-28_191956" src="https://github.com/qiye45/wechatDownload/assets/161593267/d876e690-f9c3-4644-902c-6da6461786e5">

**Comment by qiye45** [comment]
> 下载文章一起出现 获取 密钥失败 <img alt="2024-02-28_191956" width="549" src="https://private-user-images.githubusercontent.com/161593267/308537990-d876e690-f9c3-4644-902c-6da6461786e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTM5MTYsIm5iZiI6MTcwOTM1MzYxNiwicGF0aCI6Ii8xNjE1OTMyNjcvMzA4NTM3OTkwLWQ4NzZlNjkwLWY5YzMtNDY0NC05MDJjLTZkYTY0NjE3ODZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwNDI2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzI4MmIzMzEzODcxYzRlYWFiODFjODA3Mjk2MDJlNTk5ZWZlNjUwNDkxNTQwM2FhZDA1YTM4ZThjOTlkMzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.22n175fJ6S9uQnpGg3Lio1xHJGXvIDtY9E6PJDJ8tKU">

看看下面的使用教程咯

**Comment by qiye45** [comment]
导出表格数据2.2已经有啦

**Comment by qiye45** [comment]
想下载哪些网页呢，我先看看

**Comment by qiye45** [comment]
2.3加上下载任意网页啦
![image](https://github.com/qiye45/wechatDownload/assets/138199658/426dd312-b28a-4683-b722-fef51a480658)
![image](https://github.com/qiye45/wechatDownload/assets/138199658/08897837-45f6-4096-9fd4-dcbcd85473e3)
![image](https://github.com/qiye45/wechatDownload/assets/138199658/49e5a132-ec34-4573-839b-04779eda457f)
