### ISSUE TITLE
get 公众号id失败 显示操作频繁稍后再试

### ISSUE THREAD

**Issue by vovosunny** [qiye45/wechatDownload#252]
描述该错误
对该错误的简明扼要的描述。

链接和截图
添加链接和截图以帮助解释你的问题。

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by vovosunny** [comment]
![Uploading IMG_20241207_233022.jpg…]()

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416

**Comment by Bhjkgbn** [comment]
前两步都成功，到密钥这里点进去就操作繁忙，请稍候再试，但是显示操作繁忙，请稍后再试，但是我已经过了好几个小时再试，也不行
![QQ图片20241211153822](https://github.com/user-attachments/assets/6afc5438-e987-4731-b9e6-48d49f85a436)

**Comment by Bhjkgbn** [comment]
在这一步点进去后，获取的文章没有按照我选定的时间范围来，我选定的是2020年，出来的是2024年的
