### ISSUE TITLE
最新版软件已出错

### ISSUE THREAD

**Issue by bigdan05** [qiye45/wechatDownload#253]
可以识别公众号。钥匙也能拿到。但是无法导出word，pdf也不行。全部勾选之后只导出了MD文件和网址文件

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416

**Comment by bigdan05** [comment]
> [#9（评论）](https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416)
用微信的浏览器，没有开代理。就一个微信。放在F盘。目录没空格。有选HTML。还是无法导出word。
