### ISSUE TITLE
下载老提示防止被限制！

### ISSUE THREAD

**Issue by aiwuoo** [qiye45/wechatDownload#254]
开始只下载封面图，没有内容，重新下载老提示这个， 单篇下载没问题。。![112211](https://github.com/user-attachments/assets/f7e98456-0c1b-4bf7-aca8-53755d415bd1)

**Comment by qiye45** [comment]
应该下载完了。要重新下载，开始页数填 -1

**Comment by firstuanl** [comment]
3.5有这个问题，下载第一批之后，一直暂停
