### ISSUE TITLE
获取公众号ID后，获取秘钥失败

### ISSUE THREAD

**Issue by herohunter** [qiye45/wechatDownload#258]
3.4版本，获取公众号ID成功，单篇下载成功，但希望批量下载时获取秘钥一直失败，试过N多次都是一样的。

![image](https://github.com/user-attachments/assets/50abd32d-6deb-47e8-9e24-3fc8af800c76)

**Comment by yklbigdata** [comment]
同问，一直获取不了

**Comment by qiye45** [comment]
换台电脑试试
