### ISSUE TITLE
无法导出word

### ISSUE THREAD

**Issue by bigdan05** [qiye45/wechatDownload#260]
秘钥成功获取。但是怎么都无法导出word。选项全部勾选了。用的微信浏览器。文件夹也没空格。软件放在F盘里。也没有开代理。只有一个微信。且导出只有md格式和mhtml两种。微信版本是3.9.12.17

![1](https://github.com/user-attachments/assets/acb826a3-d91d-400f-bd92-29bcd944b53f)
![2](https://github.com/user-attachments/assets/eb65e6dc-0df7-44fe-b06b-a1b8cf8d316d)
![3](https://github.com/user-attachments/assets/b8f48298-3ede-41a1-bcb7-1354ac71a16e)

**Comment by qiye45** [comment]
下那个压缩包的

**Comment by bigdan05** [comment]
> 下那个压缩包的

我就是下载的压缩包，夸克的那个

**Comment by bigdan05** [comment]
> 下那个压缩包的

如果是让我下载wechatDownload-main，我下了，但是那个我不会用诶

**Comment by bigdan05** [comment]
> 下那个压缩包的

我把夸克的放进原生压缩包里。可以用了

**Comment by wysd222** [comment]
我也遇到了同样的问题，请问具体是怎么解决的呢？
