### ISSUE TITLE
好像一个微信号只能爬一次？一次爬的文章数量有限制？貌似用完就废了？

### ISSUE THREAD

**Issue by blackdogamo** [qiye45/wechatDownload#268]
我用的是最新的2.3版的工具。
我的目标公众号  历史文章特别多。
第一次，我用一个微信号爬了3个月的文章量。
然后我想继续爬时，发现不能爬了，一直是“为防止被发现 暂停十几秒”
然后就一直暂停，没能再开始
我重启多遍后 还是如此。
我只能换一个微信号，就又能成功下载文章了。
（幸好我号多）

有没有什么聪明办法，比如可以选择 “龟速但安全”的选项，让它慢慢爬历史文章🐢🐢🐢

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416
