### ISSUE TITLE
一旦批量下载就会闪退

### ISSUE THREAD

**Issue by Supersirli** [qiye45/wechatDownload#28]
有时能下几篇，也会出现提示等待十几秒，最后不出意外都闪退了

**Comment by qiye45** [comment]
试试2.2版本哒

**Comment by qiye45** [comment]
看看这个issue ：https://github.com/qiye45/wechatDownload/issues/9

**Comment by Supersirli** [comment]
我用的就是最新版的2.2哇 从你这下载的

**Comment by qiye45** [comment]
看看这个issue ：https://github.com/qiye45/wechatDownload/issues/9

**Comment by Supersirli** [comment]
根据#9 这次下了49篇推文，谢谢哥，虽然还是闪退了跟下载过程中间跳过了一些推文

**Comment by qiye45** [comment]
截个图看看吧，这么奇怪😦

**Comment by Supersirli** [comment]
啊？这个咋截屏 ？闪屏不是突然就没了吗，而且没有任何的报错
 

Uploading 2024-03-19 22 10 28.mp4…

这个是刚刚发现的一个新bug 暂停40秒 过了三四分钟还没有开始

**Comment by Supersirli** [comment]
https://github.com/qiye45/wechatDownload/assets/161188415/a3c45914-b60a-4cd5-a958-7c795fc66fb5

**Comment by Supersirli** [comment]
https://github.com/qiye45/wechatDownload/assets/161188415/a3c45914-b60a-4cd5-a958-7c795fc66fb5

**Comment by qiye45** [comment]
时间设置错啦😦

**Comment by qiye45** [comment]
左边是起始时间，右边是结束时间

**Comment by Supersirli** [comment]
ok谢谢哥 被我自己蠢到了，
![image](https://github.com/qiye45/wechatDownload/assets/161188415/11397327-aa47-4b77-acb5-33b6391e2717)
刚刚下了一下崩溃了

**Comment by Supersirli** [comment]
谢谢哥 放弃挣扎了 也下的差不多了，够用了（再次感谢！）

**Comment by qiye45** [comment]
(・ω< )★
