### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by viccccctu** [qiye45/wechatDownload#29]
请问2.2版本在哪里下载

**Comment by qiye45** [comment]
release 在网页右边



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 晚上9:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 下载 (Issue #29)




 
请问2.2版本在哪里下载

**Comment by viccccctu** [comment]
> release 在网页右边
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月12日(周二) 晚上9:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qiye45/wechatDownload] 下载 (Issue #29) 请问2.2版本在哪里下载 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

实在不好意思，我刚才下拉没看到assets，现在找到了。非常感谢，耽误您时间了。
