### ISSUE TITLE
软件打不开

### ISSUE THREAD

**Issue by jxltyang** [qiye45/wechatDownload#32]
系统: mac 13.6.1
运行环境: parallels Desktop  中的  win7

**Comment by jxltyang** [comment]
运行这个软件是需要安装什么前置软件吗

**Comment by qiye45** [comment]
win10 win11应该都行哒



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月19日(周二) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 软件打不开 (Issue #32)




 
系统: mac 13.6.1
 运行环境: parallels Desktop  中的  win7
