### ISSUE TITLE
大佬你好，有没有办法把公众号文章的长链接也导出来啊

### ISSUE THREAD

**Issue by fuzhihong2002** [qiye45/wechatDownload#34]
大佬你好，有没有办法把公众号文章的长链接也导出来啊

**Comment by qiye45** [comment]
截个图看看吧

**Comment by fuzhihong2002** [comment]
就是这个会把所有的内容都保存下来，但是我只要里面的一部分内容就好了。我一直都是用公众号平台获取的文章的长链接来抓取的内容，不过每天搞个一千来条就会被限制，想问一下这个获取到公众号id后也是靠获取到链接来定位到保存的内容吗？还是别的办法/(ㄒoㄒ)/~~

**Comment by qiye45** [comment]
选2.导出表格，这个是导出Excel表哒



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月22日(周五) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 大佬你好，有没有办法把公众号文章的长链接也导出来啊 (Issue #34)




 
就是这个会把所有的内容都保存下来，但是我只要里面的一部分内容就好了。我一直都是用公众号平台获取的文章的长链接来抓取的内容，不过每天搞个一千来条就会被限制，想问一下这个获取到公众号id后也是靠获取到链接来定位到保存的内容吗？还是别的办法/(ㄒoㄒ)/~~

**Comment by fuzhihong2002** [comment]
原来有，感谢大佬❤
