### ISSUE TITLE
不会提示下载完了，而是一直暂停n秒

### ISSUE THREAD

**Issue by HCBLY** [qiye45/wechatDownload#35]
一直提示暂停
![微信截图_20240326143805](https://github.com/qiye45/wechatDownload/assets/95267549/a7e9a97f-a5cc-4246-a890-8ff2b8cfe32d)

**Comment by qiye45** [comment]
可能是下载完了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月26日(周二) 下午2:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 不会提示下载完了，而是一直暂停n秒 (Issue #35)




 
一直提示暂停
 _20240326143805.png (view on web)
