### ISSUE TITLE
下载闪退

### ISSUE THREAD

**Issue by HawaiiGit** [qiye45/wechatDownload#36]
2.2版本下载闪退，操作系统windows11

**Comment by qiye45** [comment]
看看 https://github.com/qiye45/wechatDownload/issues/9



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月29日(周五) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 下载闪退 (Issue #36)




 
2.2版本下载闪退，操作系统windows11
