### ISSUE TITLE
对 批量下载功能 的建议

### ISSUE THREAD

**Issue by midpoint** [qiye45/wechatDownload#4]
因为批量下载默认是全部文章，如果文章多就要花很多时间，建议添加一个选项：
下载最近多少篇文章 或者 下载某个时间段的文章。

谢谢！工具很好用。

**Comment by qiye45** [comment]
下个版本会加上间隔时间调整

**Comment by qiye45** [comment]
感谢建议Thanks♪(･ω･)ﾉ
