### ISSUE TITLE
使有正常，就是窗口太小了。

### ISSUE THREAD

**Issue by 23456wangyawen** [qiye45/wechatDownload#40]
应用界面重新设计一下，以适应SurfaceBook. 3000X2000的分辨率。在此设备上，窗口的按钮上的字，及网址字符完全看不清。最大化窗口，只占屏幕的8分之一。小到无法看。。。

**Comment by qiye45** [comment]
下个版本我修一下Σ( ￣□￣||)<

**Comment by qiye45** [comment]
2.4在2k分辨率下没问题啦，要不加个群看看3000X2000下怎么样吧 https://t.me/changfengbox
