### ISSUE TITLE
单项下载，网址每次要全选删除再新粘贴，很麻烦。

### ISSUE THREAD

**Issue by 23456wangyawen** [qiye45/wechatDownload#41]
单项下载，网址每次要全选删除再新粘贴，每次，先删就旧网址，再粘贴新的，很麻烦。能不能调用剪贴板，自动网址填上替换旧网址，

**Comment by qiye45** [comment]
下个版本我加个选项咯，可以ctrl+a全选再ctrl+v粘贴

**Comment by qiye45** [comment]
2.4版本加上自动监听剪切板功能啦
![image](https://github.com/qiye45/wechatDownload/assets/138199658/9d1d1e10-9a04-47d8-85b9-70f432bc5c12)
