### ISSUE TITLE
为什么下载之后只有html没有doc

### ISSUE THREAD

**Issue by yan-gemini** [qiye45/wechatDownload#42]
单篇下载之后，只有html，但是UI上勾选了导出为pdf和doc
![image](https://github.com/qiye45/wechatDownload/assets/17723860/caa26ef5-be09-41bd-805a-c428c7840e49)

**Comment by yan-gemini** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/17723860/e19470ac-e13d-4721-828f-4f4d84f81925)

**Comment by yan-gemini** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/17723860/45b66b45-27b0-42b1-aa75-d973a4fe6408)

**Comment by qiye45** [comment]
目录不能有空格



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月9日(周二) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 为什么下载之后只有html没有doc (Issue #42)




 
单篇下载之后，只有html，但是UI上勾选了导出为pdf和doc
 image.png (view on web)

**Comment by yan-gemini** [comment]
果然，绝对路径不能带空格，谢谢

**Comment by wbj20** [comment]
> 果然，绝对路径不能带空格，谢谢
啥意思，那个不能有空格，我也下载不了word版本、

**Comment by qiye45** [comment]
> > 果然，绝对路径不能带空格，谢谢
> > 啥意思，那个不能有空格，我也下载不了word版本、

存放文件的目录
![image](https://github.com/qiye45/wechatDownload/assets/138199658/7f332422-b186-4438-a4dc-d6b7f1504de8)

**Comment by wbj20** [comment]
好的，已经解决了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qiye45 ***@***.***&gt;
发送时间: 2024年4月9日 23:19
收件人: qiye45/wechatDownload ***@***.***&gt;
抄送: wbj20 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [qiye45/wechatDownload] 为什么下载之后只有html没有doc (Issue #42)





   
果然，绝对路径不能带空格，谢谢
 啥意思，那个不能有空格，我也下载不了word版本、
   
存放文件的目录
 image.png (view on web)

**Comment by llywjngit** [comment]
> > > 果然，绝对路径不能带空格，谢谢
> > > 啥意思，那个不能有空格，我也下载不了word版本、
> 
> 存放小目录 ![图像](https://private-user-images.githubusercontent.com/138199658/320904924-7f332422-b186-4438-a4dc-d6b7f1504de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzQwOTMsIm5iZiI6MTcxODA3Mzc5MywicGF0aCI6Ii8xMzgxOTk2NTgvMzIwOTA0OTI0LTdmMzMyNDIyLWIxODYtNDQzOC1hNGRjLWQ2YjdmMTUwNGRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwMjQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWQ2ZDJhMWI3NDkxNTM4MWZjMTkzMmY3ZjRjZTQzZDIwMzYxZDQyNzkxNzUwMjg3ZmI1ZmQzNTE4MTRjYzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KD85TTl8xg8rj4aZCExiibm-doqvU0M7Qku6pTZh3Dc)

请问是文件夹不能有空格还是，链接不能有空格

**Comment by qiye45** [comment]
> 请问是文件夹不能有空格还是，链接不能有空格
文件夹

**Comment by llywjngit** [comment]
> > 请问是文件夹不能有空格还是，链接不能有空格
> 
> 文件夹

谢谢

**Comment by Matsubokuri** [comment]
> 果然，绝对路径不能带空格，谢谢

请问有解决吗，怎么修改存放文件的目录呢

**Comment by KingAllen613** [comment]
怎么导出都是封面，没有文章？

**Comment by mobius6799** [comment]
为什么没有空格也下载不成功啊
<img width="1721" height="775" alt="Image" src="https://github.com/user-attachments/assets/538efd41-2c43-40fd-920d-94400ed50025" />
