### ISSUE TITLE
阅读量为0，跳过下载

### ISSUE THREAD

**Issue by liumoze** [qiye45/wechatDownload#43]
2.3版本

**Comment by liumoze** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/49368205/1cca7f16-6615-496c-94d5-d1a486c37cd4)

**Comment by qiye45** [comment]
意思是阅读量超过0的文章，会下载



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月9日(周二) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 阅读量为0，跳过下砸 (Issue #43)




 
2.3版本

**Comment by qiye45** [comment]
改成-999试一试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月9日(周二) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 阅读量为0，跳过下砸 (Issue #43)




 
2.3版本

**Comment by qiye45** [comment]
发一下公众号链接，我试一试吧

**Comment by liumoze** [comment]
> 试试2.2版本哒

我再试试
