### ISSUE TITLE
下载闪崩

### ISSUE THREAD

**Issue by wodeqiche2007** [qiye45/wechatDownload#44]
![4](https://github.com/qiye45/wechatDownload/assets/44803921/bb6c8fa4-91e0-4084-b5e5-52700fe6171b)
第一，单篇文章，点击下载，出现图片提示的错误。第二，然后打开微信文章之后，监控下载，获得文章mid后，点击监控下载闪崩

**Comment by qiye45** [comment]
提错仓库啦
