### ISSUE TITLE
系统兼容

### ISSUE THREAD

**Issue by JadePureOne** [qiye45/wechatDownload#47]
有计划推出适用于linux或docker的版本吗

**Comment by qiye45** [comment]
微信没有Linux版本吧 Σ( ￣□￣||)<



---原始邮件---
发件人: "Jade Pure ***@***.***&gt;
发送时间: 2024年4月15日(周一) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 系统兼容 (Issue #47)




 
有计划推出适用于linux或docker的版本吗
