### ISSUE TITLE
你好下载完成但是文档是空的·，是什么原因

### ISSUE THREAD

**Issue by 50558049** [qiye45/wechatDownload#48]
你好下载完成但是文档是空的·，是什么原因

**Comment by qiye45** [comment]
截个图看看，发一下链接。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月15日(周一) 晚上6:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 你好下载完成但是文档是空的·，是什么原因 (Issue #48)




 
你好下载完成但是文档是空的·，是什么原因
