### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by daheitian** [qiye45/wechatDownload#49]
批量下载会崩溃，闪退

**Comment by qiye45** [comment]
看看#9，把梯子关了试试



---原始邮件--
发件人: "jijiang ***@***.***&gt;
发送时间: 2024年4月17日(周三) 中午11:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 崩溃问题 (Issue #49)




 
批量下载会崩溃，闪退

**Comment by qiye45** [comment]
带上链接...



---原始邮件---
发件人: "jijiang ***@***.***&gt;
发送时间: 2024年4月17日(周三) 中午11:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 崩溃问题 (Issue #49)




 
批量下载会崩溃，闪退
