### ISSUE TITLE
显示有病毒

### ISSUE THREAD

**Issue by xue160709** [qiye45/wechatDownload#51]
![image](https://github.com/qiye45/wechatDownload/assets/5611511/96fdd73b-7d76-4ce8-99cc-63aa45548f0f)

**Comment by qiye45** [comment]
#21



---原始邮件---
发件人: "Zhirong ***@***.***&gt;
发送时间: 2024年4月17日(周三) 下午2:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 显示有病毒 (Issue #51)




 
image.png (view on web)
