### ISSUE TITLE
为了防止访问公众号被限制，暂停15秒。为啥无限出现这个

### ISSUE THREAD

**Issue by gewuagewua** [qiye45/wechatDownload#53]
<img src="https://img.chkaja.com/58f3d5712e96a7ec.png" alt="58f3d5712e96a7ec.png" title="58f3d5712e96a7ec.png" />

**Comment by gewuagewua** [comment]
每次都是下载最后一篇文章的时候无限出现，其他文章虽然也有但都会继续下载

**Comment by qiye45** [comment]
这个是下载完了，下个版本我优化一下(=・ω・=)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月18日(周四) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 为了防止访问公众号被限制，暂停15秒。为啥无限出现这个 (Issue #53)

**Comment by gewuagewua** [comment]
> 这个是下载完了，下个版本我优化一下(=・ω・=)
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月18日(周四) 晚上6:05 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qiye45/wechatDownload] 为了防止访问公众号被限制，暂停15秒。为啥无限出现这个 (Issue #53) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好耶

**Comment by qiye45** [comment]
2.4版本会修复无限出现暂停的问题啦

**Comment by qhgy** [comment]
> 2.4版本会修复无限出现暂停的问题啦

我直接下载某个公众号（饕餮海投资）2020年的文章 结果一篇也没下载

**Comment by qiye45** [comment]
> 饕餮海投资

先看看视频...
![image](https://github.com/qiye45/wechatDownload/assets/138199658/651fc32f-5720-47d9-8d0c-199e1575ded1)

**Comment by gewuagewua** [comment]
> 我直接下载某个公众号（饕餮海投资）2020年的文章 结果一篇也没下载
有时候确实会这样，再下一次就好了
