### ISSUE TITLE
请问作者有没有考虑这个功能：同一个作者的文章整合成一个PDF文件

### ISSUE THREAD

**Issue by gewuagewua** [qiye45/wechatDownload#55]
**描述你想要的功能**
带可跳转的目录的那种，我觉得这个功能实用性非常强！求作者大哥考虑一下

**Comment by gewuagewua** [comment]
我是这么想的，因为本来公众号的文章都是短文，长点的也不过一两万字，每次频繁的打开PDF文件确实有点麻烦，尤其是文章多一点的作者。
整合进一个PDF不仅直观而且可以省去很多重复操作！

**Comment by qiye45** [comment]
可以先试试pdf合并的软件哟，加上pdf处理软件会大很多，后面看看能不能加上咯
https://github.com/wmjordan/PDFPatcher
