### ISSUE TITLE
非开源项目一律按照投毒处理！

### ISSUE THREAD

**Issue by paynepang** [qiye45/wechatDownload#56]
非开源项目一律按照投毒处理！
非开源项目一律按照投毒处理！
非开源项目一律按照投毒处理！
非开源项目一律按照投毒处理！
非开源项目一律按照投毒处理！
非开源项目一律按照投毒处理！

**Comment by kanadeblisst00** [comment]
作者拿刀强迫你下载并运行了？白嫖还这么有理，八成是倒卖党
