### ISSUE TITLE
程序内Win64.Trojan.Agent.Twhl 木马

### ISSUE THREAD

**Issue by zxcfdxc** [qiye45/wechatDownload#57]
腾讯管家报毒怎么回事儿

**Comment by qiye45** [comment]
#21



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月20日(周六) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 程序内Win64.Trojan.Agent.Twhl 木马 (Issue #57)




 
腾讯管家报毒怎么回事儿

**Comment by qiye45** [comment]
因为打包成了单文件版本，不好解决...
![image](https://github.com/qiye45/wechatDownload/assets/138199658/21796083-7ae2-4da5-88c0-6cc126127381)
