### ISSUE TITLE
我完全按照guideline中的指示操作，发现只能下载单篇文章。可以成功获取到公众号ID，但是无法批量下载。

### ISSUE THREAD

**Issue by stonexie** [qiye45/wechatDownload#58]
非常感谢大神开发出这么牛逼的工具。期待已久，不过我只能单篇下载，在批量下载时，从报错来看，可以获取到公众号下的每一篇文章，但是每一篇文章的下载都是报错。请大神指点可能是为什么呢？

**Comment by stonexie** [comment]
期待大神回答，我会经常回来看看的

**Comment by stonexie** [comment]
感谢大神回复，我使用的是最新的2.3版本。我想下载这个微信公众号的文章，于是
1）我在输入框中输入：https://mp.weixin.qq.com/s/1jyduuuQNW3rqvuK7ok-Fw 并且点击获取公众号ID
2）待到提示出现：获取公众号历史消息页面成功，请在微信打开复制的链接：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU2MDI5MjAxMA==&scene=124#wechat_redirect
3）然后我拷贝2）中的链接到微信，并且使用微信内置的浏览器打开此链接。然后它就提示获取秘钥成功，我点击批量下载文章，然后就全部报错。
但是我试过如果是单篇下载，是可以下载成功的，只是提示下载评论错误。

![image](https://github.com/qiye45/wechatDownload/assets/9813830/3f526c88-dec2-49f0-b125-59c385fd878e)
![image](https://github.com/qiye45/wechatDownload/assets/9813830/745446d7-0835-4443-a891-76ae22fb262b)

**Comment by qiye45** [comment]
微信加上网络验证了，可能要下个版本修啦
![image](https://github.com/qiye45/wechatDownload/assets/138199658/9813a075-9072-4a88-93b9-15778a0283bb)

**Comment by qiye45** [comment]
2.4版本修好啦，可以先用单篇下载，或者等下个版本更新哟 
![image](https://github.com/qiye45/wechatDownload/assets/138199658/aa8032c2-b340-46fa-96ef-406f1fb2d1fb)

**Comment by qiye45** [comment]
2.4更新啦

**Comment by stonexie** [comment]
大佬牛逼，这么快就修好了啊，我滑跪过来感谢大神！！！！

**Comment by qslwp** [comment]
获取秘钥失败 2.4
![Uploading UUR{6P2ZC{3ZF4W2{SUK)QF.png…]()

**Comment by qslwp** [comment]
![UUR{6P2ZC{3ZF4W2{SUK)QF](https://github.com/qiye45/wechatDownload/assets/39366093/bb0fe79f-4039-4858-bf06-e8b1b414a9cb)
我完全按照guideline中的指示操作，获取秘钥失败

**Comment by qiye45** [comment]
#61



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 我完全按照guideline中的指示操作，发现只能下载单篇文章。可以成功获取到公众号ID，但是无法批量下载。 (Issue #58)




 
UUR.6P2ZC.3ZF4W2.SUK.QF.png (view on web)
 我完全按照guideline中的指示操作，获取秘钥失败

**Comment by qslwp** [comment]
我是在微信内置浏览器打开的，没开梯子，就是获取秘钥失败
