### ISSUE TITLE
无法获取秘钥

### ISSUE THREAD

**Issue by xtbggqy** [qiye45/wechatDownload#61]
![image](https://github.com/qiye45/wechatDownload/assets/150650455/3c894eb0-f3d7-46e4-8d41-b5f956c2602b)

微信文章链接：https://mp.weixin.qq.com/s/yBwtmCEf_FXD0q2vQ0F77g

单篇文章可下载，可获取公众号ID
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzUxNjg4NDEzNA==&scene=124#wechat_redirect

打开复制链接后，无法获取秘钥
注：梯子已关闭，在国内

**Comment by qiye45** [comment]
先看看视频教程咯，要用微信自带的浏览器打开



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月22日(周一) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 无法获取秘钥 (Issue #61)




 
image.png (view on web)
 微信文章链接：https://mp.weixin.qq.com/s/yBwtmCEf_FXD0q2vQ0F77g
 单篇文章可下载，可获取公众号ID
 https://mp.weixin.qq.com/mp/profile_ext?action=home&amp;__biz=MzUxNjg4NDEzNA==&amp;scene=124#wechat_redirect
 打开复制链接后，无法获取秘钥
 注：梯子已关闭，在国内

**Comment by xtbggqy** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/150650455/1be9f51c-8e49-4f5f-a953-6ca9d5296b2e)

是用微信自带浏览器打开的，打开后出现这个界面

**Comment by qiye45** [comment]
没问题哒， 看看这个&nbsp;https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月22日(周一) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 无法获取秘钥 (Issue #61)




 
image.png (view on web)
 微信文章链接：https://mp.weixin.qq.com/s/yBwtmCEf_FXD0q2vQ0F77g
 单篇文章可下载，可获取公众号ID
 https://mp.weixin.qq.com/mp/profile_ext?action=home&amp;__biz=MzUxNjg4NDEzNA==&amp;scene=124#wechat_redirect
 打开复制链接后，无法获取秘钥
 注：梯子已关闭，在国内

**Comment by qiye45** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月22日(周一) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 无法获取秘钥 (Issue #61)




 
image.png (view on web)
 微信文章链接：https://mp.weixin.qq.com/s/yBwtmCEf_FXD0q2vQ0F77g
 单篇文章可下载，可获取公众号ID
 https://mp.weixin.qq.com/mp/profile_ext?action=home&amp;__biz=MzUxNjg4NDEzNA==&amp;scene=124#wechat_redirect
 打开复制链接后，无法获取秘钥
 注：梯子已关闭，在国内

**Comment by xiaomading333** [comment]
同上问题，无法获取秘钥

**Comment by qslwp** [comment]
> 同上问题，无法获取秘钥

解决了吗 老哥

**Comment by qiye45** [comment]
先合并到https://github.com/qiye45/wechatDownload/issues/63 啦
