### ISSUE TITLE
无法获取秘钥，大佬能说一下你的测试微信版本号吗？

### ISSUE THREAD

**Issue by qslwp** [qiye45/wechatDownload#63]
没开梯子，微信内打开的链接，无法获取秘钥。

大佬能说一下你的测试微信版本号吗？

**Comment by qiye45** [comment]
看看这个 https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiye45/wechatDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 中午11:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiye45/wechatDownload] 无法获取秘钥，大佬能说一下你的测试微信版本号吗？ (Issue #63)





 
没开梯子，微信内打开的链接，无法获取秘钥。
 
大佬能说一下你的测试微信版本号吗？

**Comment by qslwp** [comment]
> 看看这个 [#9 (comment)](https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "qiye45/wechatDownload" ***@***.***&gt;; 发送时间:&nbsp;2024年4月23日(星期二) 中午11:24 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[qiye45/wechatDownload] 无法获取秘钥，大佬能说一下你的测试微信版本号吗？ (Issue #63) 没开梯子，微信内打开的链接，无法获取秘钥。 大佬能说一下你的测试微信版本号吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

看了呀，所有issues我打看了试了一遍，还不行。所以问问微信版本号。

**Comment by qiye45** [comment]
最新版没问题哒
![image](https://github.com/qiye45/wechatDownload/assets/165148036/6d8011fa-a4a9-48df-a738-f939f1fb5f09)
![image](https://github.com/qiye45/wechatDownload/assets/165148036/ee4da29f-f5a4-431d-be1a-d736aadf047a)






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "qiye45/wechatDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 中午11:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiye45/wechatDownload] 无法获取秘钥，大佬能说一下你的测试微信版本号吗？ (Issue #63)





 
没开梯子，微信内打开的链接，无法获取秘钥。
 
大佬能说一下你的测试微信版本号吗？

**Comment by qslwp** [comment]
奇怪了

**Comment by qiye45** [comment]
或者加群看看咯
![image](https://github.com/qiye45/wechatDownload/assets/165148036/383e811d-8985-40bc-8867-02b207214268)
![image](https://github.com/qiye45/wechatDownload/assets/165148036/f5e661aa-57d4-4bb7-a9bb-180c933283c5)










------------------ 原始邮件 ------------------
发件人:                                                                                                                        "qiye45/wechatDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 中午11:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiye45/wechatDownload] 无法获取秘钥，大佬能说一下你的测试微信版本号吗？ (Issue #63)





 
没开梯子，微信内打开的链接，无法获取秘钥。
 
大佬能说一下你的测试微信版本号吗？
