### ISSUE TITLE
勾了导出word无反应

### ISSUE THREAD

**Issue by linjet2022** [qiye45/wechatDownload#64]
2.4版 导出word已打勾下载的文件中没有word文档

**Comment by qiye45** [comment]
#42



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 中午12:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 勾了导出word无反应 (Issue #64)




 
2.4版 导出word已打勾下载的文件中没有word文档
