### ISSUE TITLE
为什么导出表格数据，数据采集不完整

### ISSUE THREAD

**Issue by Elaina8023** [qiye45/wechatDownload#65]
请教一下，为什么下载下来的数据，只要少数几个呢？
公众号数据没发下载全，尝试了间隔10秒，40秒采集，也是采集不完全。
[2024-04-23-222730.csv](https://github.com/qiye45/wechatDownload/files/15078504/2024-04-23-222730.csv)

**Comment by qiye45** [comment]
我看全了呢
![image](https://github.com/qiye45/wechatDownload/assets/138199658/7d21ae86-533a-4cd8-81ff-db70a2b4fe01)
![image](https://github.com/qiye45/wechatDownload/assets/138199658/02c3648b-1eff-43be-992a-c21c1126ef25)

**Comment by qiye45** [comment]
下个版本我修一下吧 ｡ﾟ(ﾟ´Д｀)ﾟ｡

**Comment by Elaina8023** [comment]
好的感谢博主~

**Comment by qiye45** [comment]
在看的数据获取 https://github.com/qiye45/wechatDownload/issues/67

**Comment by qiye45** [comment]
![image](https://github.com/qiye45/wechatDownload/assets/138199658/5817ff67-dff4-4e67-97ea-06821cbf6431)
2.5版本修复啦
