### ISSUE TITLE
win11 安全中心报病毒

### ISSUE THREAD

**Issue by taosapp** [qiye45/wechatDownload#66]
已阻止威胁
2024/4/23 22:41
**严重**
已检测:Trojan:Win32/Sabsik.FL.A!ml
状态: 已隔离
隔离的文件在不会损害设备的受限区域内。系统将自动删除它们。
日期:2024/4/23 22:41
详细信息:这个程序很危险，而且执行来自攻击者的命令，
受影响的项目:
file: E:\software\wechatDownload2.4\微信公众号文章批量下载工具2.4.exe
了解更多信息

**Comment by qiye45** [comment]
我看看后面怎么解决吧

**Comment by gwl7810** [comment]
Trojan:Win32/Wacatac.H!ml ,win11报告病毒

**Comment by qiye45** [comment]
最快解决方法，给微软交250刀的保护费 (¦3【▓▓】

**Comment by emaisi** [comment]
win10也报毒了

**Comment by emaisi** [comment]
2.4版本在win10上也报毒

**Comment by wcctml** [comment]
微软交250刀请问是什么认证？有网页能发一下吗。谢谢

**Comment by tedonggo** [comment]
我也是，360提示报告病毒
