### ISSUE TITLE
获取秘钥环节不稳定

### ISSUE THREAD

**Issue by StudyDayDayUpA** [qiye45/wechatDownload#67]
开始获取秘钥...
获取秘钥失败...请先在微信打开复制的链接

按照操作手册进行操作，发现这个环节不是很稳定，有时候能容易获取到秘钥，有时候获取不到或者需要获取很久才行。希望优化，让软件越来越好用。

**Comment by StudyDayDayUpA** [comment]
另外，这边还发现一个bug，在批量下载的时候有些文章的阅读、点赞等数据获取不到（有数据，但都显示为0）。
另外希望能增加：在看的数据获取。

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/65 啦
