### ISSUE TITLE
支持多个公众号不同文章下载

### ISSUE THREAD

**Issue by iceblue0227** [qiye45/wechatDownload#69]
比如：
公众号A里的文章标题为123的
公众号B里的文章标题为234的

这样，多个公众号不同文章的同时下载。现在只能一个个下载，能不能都把链接粘贴要txt里，再贴到软件里，或把txt文档拖拽到软件里？

**Comment by qiye45** [comment]
#60



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 上午9:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 支持多个公众号不同文章下载 (Issue #69)




 
比如：
 公众号A里的文章标题为123的
 公众号B里的文章标题为234的
 
这样，多个公众号不同文章的同时下载。现在只能一个个下载，能不能都把链接粘贴要txt里，再贴到软件里，或把txt文档拖拽到软件里？
