### ISSUE TITLE
2.4版本闪退

### ISSUE THREAD

**Issue by dahuya** [qiye45/wechatDownload#70]
下载几篇之后会自动退出

**Comment by qiye45** [comment]
先试试旧版本咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 中午12:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 2.4版本闪退 (Issue #70)




 
下载几篇之后会自动退出

**Comment by qiye45** [comment]
可能下载2.4下载封面 音频 视频的功能不稳定，先试试2.3咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 中午12:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 2.4版本闪退 (Issue #70)




 
下载几篇之后会自动退出

**Comment by dahuya** [comment]
经本人测试，2.3版本依旧会闪退

**Comment by qiye45** [comment]
录个视频看看...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 下午2:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 2.4版本闪退 (Issue #70)




 
经本人测试，2.3版本依旧会闪退

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/76 啦
