### ISSUE TITLE
可以考虑增加是否下载图片跟视频的选项，延续上次下载

### ISSUE THREAD

**Issue by OranHub** [qiye45/wechatDownload#72]
**描述你想要的功能**
有的用户是不需要下载图片跟视频的，只需要文字内容。  而且好像有BUG下载了一两个小时就不动了，也没有提示报错无法下载的原因，好像也没有延续上次下载的按钮

**Comment by qiye45** [comment]
下个版本我加上延续上次下载的功能吧(=・ω・=)

**Comment by qiye45** [comment]
确实好像有bug，会遇到中断下载的问题 Σ_(꒪ཀ꒪」∠)_

**Comment by qiye45** [comment]
mark一下
跳过已经下载的文章 https://github.com/qiye45/wechatDownload/issues/91

**Comment by hrbagang** [comment]
> **描述你想要的功能** 有的用户是不需要下载图片跟视频的，只需要文字内容。 而且好像有BUG下载了一两个小时就不动了，也没有提示报错无法下载的原因，好像也没有延续上次下载的按钮

现在最新的2.6版本，可以下载照片和视频吗？
我的下载选项，如下图。这种选项设置下，看了下每个导出的html文件，size都不大，不像是下载了图片的样子。。。
![image](https://github.com/qiye45/wechatDownload/assets/29511872/22357afd-863d-4eb6-b5a3-d35809cfab69)

**Comment by qiye45** [comment]
能下载封面和视频，在文件夹保存哒

> > **描述你想要的功能** 有的用户是不需要下载图片跟视频的，只需要文字内容。 而且好像有BUG下载了一两个小时就不动了，也没有提示报错无法下载的原因，好像也没有延续上次下载的按钮
> 
> 现在最新的2.6版本，可以下载照片和视频吗？ 我的下载选项，如下图。这种选项设置下，看了下每个导出的html文件，size都不大，不像是下载了图片的样子。。。 ![image](https://private-user-images.githubusercontent.com/29511872/338582983-22357afd-863d-4eb6-b5a3-d35809cfab69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDk3ODYsIm5iZiI6MTcxODEwOTQ4NiwicGF0aCI6Ii8yOTUxMTg3Mi8zMzg1ODI5ODMtMjIzNTdhZmQtODYzZC00ZWI2LWI1YTMtZDM1ODA5Y2ZhYjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEyMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjExN2MyNWI0Zjc1MTI5MDQ1Yzg3YWEzMDYxNTllM2MzM2MyYTZlMGE2MmVhZGZlOWM0YjhjNTEwNWY5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._JdmZ1Dz-Z_F7NzZE8IbN_s16Gi-0OKjpAg9oS4GOk4)

**Comment by qiye45** [comment]
2.7 支持跳过已下载的文章啦
