### ISSUE TITLE
下载封面、文件归类到公众号是否可以作为可选项

### ISSUE THREAD

**Issue by 23456wangyawen** [qiye45/wechatDownload#73]
下载封面、文件归类到公众号是否可以作为可选项呢？

**Comment by 23456wangyawen** [comment]
与之前版本，如果下载不同公众号的，单一文件，都在同一目录，现在归类到不同公众号下，文件夹套文件。反而麻烦了。比如我，比如在，经常要在多个公众号下寻找一些相似的文章，比如电动汽车。我希望一各个单一下载后，归类到我自已电脑的文件夹下。而现在下载到各个公众号的文件夹内，我还要一个个摘出来，反而麻烦了。建议，将封面、下载到公众号文件夹下作为用户可选项。在设置里打勾，让用户根据喜好来选择吧。

**Comment by qiye45** [comment]
可以试试旧版本哟，下载之后把封面删除就好啦(=・ω・=)

**Comment by qiye45** [comment]
是否下载封面/图片/视频的选项 合并到https://github.com/qiye45/wechatDownload/issues/72啦

**Comment by qiye45** [comment]
可以试试window自带的搜索功能，查找相似的文件
