### ISSUE TITLE
选定的下载时间范围无任何效果，中断下载的问题

### ISSUE THREAD

**Issue by OranHub** [qiye45/wechatDownload#74]
**描述该错误**
对该错误的简明扼要的描述。
选定的下载时间范围无任何效果，还是会先从最新文章慢慢的遍历到指定时间，这就是之前终止下载之后无法直接继承上一次的缓存继续下载的一个后果
**截图**
添加截图以帮助解释你的问题。
![BUG](https://github.com/qiye45/wechatDownload/assets/76681154/ef684e24-3107-4890-a232-40ebe84bcea0)

**其他信息**
在这里添加关于该问题的任何其他背景。
可以考虑增加按钮继续上次进度，增加按钮不下载图片跟视频，增加格式epub

**Comment by Reg2020** [comment]
![不知道下载什么+QQ拼音截图20240425165833](https://github.com/qiye45/wechatDownload/assets/30361321/e95a22c6-63e3-473b-9462-b97a6afb1ae7)

感觉下载了一个月的历史文章后，它就迷茫了，就不知道接下来要干嘛。时间参数是不是需要调整

同时，自定义下载时间范围好像不大奏效。手动翻页，可以翻到历史文章

**Comment by qiye45** [comment]
导出epub可以试试这个哟 https://github.com/qiye45/html2epub，支持html批量导出epub哒

**Comment by qiye45** [comment]
> ![不知道下载什么+QQ拼音截图20240425165833](https://private-user-images.githubusercontent.com/30361321/325543528-e95a22c6-63e3-473b-9462-b97a6afb1ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTEwMDEsIm5iZiI6MTcxNDA1MDcwMSwicGF0aCI6Ii8zMDM2MTMyMS8zMjU1NDM1MjgtZTk1YTIyYzYtNjNlMy00NzNiLTk0NjItYjk3YTZhZmIxYWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjY3YzljY2Q2YWJmNmEzOTUyYmRkOTUyNmI0M2ViMGIwNzM2NjFlNDQ1NzVlZjA4YjQyNjA2ZTZhZjljNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VIyspF6ZvkYS7wBnz7OyduGicRsnmzm1SHFEY-I1JoQ)
> 
> 感觉下载了一个月的历史文章后，它就迷茫了，就不知道接下来要干嘛。手动翻页，可以翻到历史文章
> 
> 同时，自定义下载时间范围好像不大奏效。时间参数是不是需要调整

下个版本我修一下吧，确实有会中断下载的问题

**Comment by qiye45** [comment]
2.5修复中断下载的问题啦
