### ISSUE TITLE
2.4及2.3至2.1版本均闪退

### ISSUE THREAD

**Issue by renkangjian** [qiye45/wechatDownload#76]
[爬取十篇左右文章后即闪退]
视频后附

https://github.com/qiye45/wechatDownload/assets/94792881/5464f43f-0773-4beb-9707-62fb4178673e

**Comment by qiye45** [comment]
奇怪了，先加群看看吧 https://t.me/changfengboxchat

**Comment by qiye45** [comment]
先试试2.5版本吧
