### ISSUE TITLE
使用中的若干问题，目录带空格，支持mhtml下载

### ISSUE THREAD

**Issue by Eyion** [qiye45/wechatDownload#77]
**描述该错误**
1.下载设置中导出为html,word,pdf,md，但实际只下载了html和md
2.下载评论失败（有评论）
3.希望能自定义设置下载目录
4.无法勾选下载评论回复
5.没有暂停下载
6.建议增加下载完成提示（成功下载数量，下载失败数量），开始下载后面没有文字了是下载完了还是卡住了，见截图
7.下载过并且仍在下载目录的文章能够选择跳过或覆盖

**截图**
![image](https://github.com/qiye45/wechatDownload/assets/26318038/8b18cc99-249d-49a7-b137-5d44a7efcfdd)
![image](https://github.com/qiye45/wechatDownload/assets/26318038/43e8abb1-03ea-4c1e-bb23-275888a0e53f)

**其他信息**
wechatDownload版本：2.4

**Comment by qiye45** [comment]
在https://github.com/qiye45/wechatDownload/issues/72 提过了

**Comment by qiye45** [comment]
其他问题在之前的issue都有解决方法哒

**Comment by qiye45** [comment]
3.自定义设置下载目录要改东西太多了...

**Comment by Eyion** [comment]
谢谢作者的回复，我想补充问问：
1.目录带空格，不知能否解决，感觉挺实用的
2.下载暂停和下载完成提示（成功下载数量，下载失败数量）这2个功能有吗？没找到，也没看到issue
3.下载过并且仍在下载目录的文章能够选择跳过或覆盖，这个没看到同样的issue
4.下载的html格式里面是没有图片和音视频的吗？如果是mhtml能否保留，感觉最好是能保持文章原有的格式及内容的完整性，您觉得呢

软件很不错，再次感谢作者的付出！

**Comment by qiye45** [comment]
下个版本我看看咯

**Comment by binjar** [comment]
导出PDF格式异常，文件内容空白，文章内容生成到了PDF文件的目录。
软件版本：2.5
测试URL：https://mp.weixin.qq.com/s/f0026S1MDjXu9lK5_dBLfA
截图：
![image](https://github.com/qiye45/wechatDownload/assets/81861926/961652db-2e6d-4879-a319-d6805bad2270)

**Comment by qiye45** [comment]
3.0支持mhtml下载啦https://github.com/qiye45/wechatDownload/blob/main/example/20240705%E7%A7%91%E6%8A%80%E7%88%B1%E5%A5%BD%E8%80%85%E5%91%A8%E5%88%8A307%E4%B8%8D%E8%A6%81%E7%9C%8B%E9%87%8DProductHunt.mhtml
