### ISSUE TITLE
提示"操作频繁，请稍后再试",如何解决?

### ISSUE THREAD

**Issue by chqaxm** [qiye45/wechatDownload#78]
打开https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU0Mzk0ODMyMQ==&scene=124#wechat_redirect页面提示"操作频繁，请稍后再试",如何解决?

**Comment by qiye45** [comment]
#20



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月29日(周一) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 提示"操作频繁，请稍后再试",如何解决? (Issue #78)




 
打开https://mp.weixin.qq.com/mp/profile_ext?action=home&amp;__biz=MzU0Mzk0ODMyMQ==&amp;scene=124#wechat_redirect页面提示"操作频繁，请稍后再试",如何解决?
