### ISSUE TITLE
win11安全中心，报病毒啊

### ISSUE THREAD

**Issue by taosapp** [qiye45/wechatDownload#8]
![屏幕截图 2024-01-08 194736](https://github.com/qiye45/wechatDownload/assets/36772/5180f774-5eb4-4a73-9313-edee5a5babf2)

**Comment by qiye45** [comment]
建议关闭安全中心，换成火绒：https://answers.microsoft.com/zh-hans/windows/forum/all/%E6%80%8E%E6%A0%B7%E5%BD%BB%E5%BA%95%E5%85%B3/1ac9435f-f254-47fa-95c5-d0a192011a33

![image](https://github.com/qiye45/wechatDownload/assets/138199658/7f6d5056-8e69-4a82-ae7a-0d63a056c943)
