### ISSUE TITLE
文件名超过30个字符会被截断，标点符号会被删去

### ISSUE THREAD

**Issue by SpaceDolphinMachineGun** [qiye45/wechatDownload#81]
**描述该错误**
文件名超过30个字符会被截断，标点符号会被删去。

**截图**
![公众号文章](https://github.com/qiye45/wechatDownload/assets/20679428/850d5bbe-b353-4da5-950b-609f91f1694d)
![下载结果](https://github.com/qiye45/wechatDownload/assets/20679428/133b01da-c7b4-4731-8184-af21f704e511)

**其他信息**
版本2.4，win7，微信3.9.10.19

**Comment by SpaceDolphinMachineGun** [comment]
如果算上自动添加的日期8个字符，那只要超过22个字符的标题，就会被截断。另外所有的标点符号都会被删掉，这个希望能够优化一下。谢谢。

**Comment by qiye45** [comment]
这个是因为window的系统限制，文件名太长或者有中文符号会出问题的

**Comment by SpaceDolphinMachineGun** [comment]
> 这个是因为window的系统限制，文件名太长或者有中文符号会出问题的
emm windows系统文件名限制不是255吗？不太清楚这个，但之前用其他类似软件是可以下载长文件名的html的。比如这个：
![示例](https://github.com/qiye45/wechatDownload/assets/20679428/99d1e46d-6379-46e9-b53f-3bbe5b5be7e0)

**Comment by qiye45** [comment]
下个版本我延长到50个字吧
