### ISSUE TITLE
公众号名称自带空格，2.4版本无法导出PDF

### ISSUE THREAD

**Issue by rhww** [qiye45/wechatDownload#83]
2.4版本默认文章下载到以公众号名称命名的文件夹中，我查看了以前的issue，需要无空格才能导出PDF，但是2.4目前是无解了，然后我尝试用2.2版本的，但是一直显示获取ID失败，建议后续版本能够下载到自定义文件夹中，避免类似的问题导致无法下载。

**Comment by qiye45** [comment]
截个图看看，带上链接。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月5日(周日) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 公众号名称自带空格，2.4版本无法导出PDF (Issue #83)




 
2.4版本默认文章下载到以公众号名称命名的文件夹中，我查看了以前的issue，需要无空格才能导出PDF，但是2.4目前是无解了，然后我尝试用2.2版本的，但是一直显示获取ID失败，建议后续版本能够下载到自定义文件夹中，避免类似的问题导致无法下载。

**Comment by rhww** [comment]
![Uploading 微信图片_20240506201846.png…]()

**Comment by qiye45** [comment]
一样的问题，先合并到 https://github.com/qiye45/wechatDownload/issues/77啦 。。。
