### ISSUE TITLE
无法下载评论 Ver2.4

### ISSUE THREAD

**Issue by tianzile** [qiye45/wechatDownload#84]
无法下载评论，这个大家能正常下载吗？
以及下载评论回复无法点击

**Comment by tianzile** [comment]
![2个问题](https://github.com/qiye45/wechatDownload/assets/42037465/7c221efc-9642-4029-a17d-41b5db00bc33)

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/52

**Comment by qiye45** [comment]
用批量下载的

**Comment by tianzile** [comment]
> 用批量下载的

感谢回复，好用了。
