### ISSUE TITLE
如果可以从txt文本中读取链接下载就好了

### ISSUE THREAD

**Issue by zct4257** [qiye45/wechatDownload#85]
**描述你想要的功能**
在txt文件中整理了许多公众号文章链接，如果单篇下载，一个个复制粘贴的话，比较慢，批量读取最佳

比如，我的txt文件中的内容如下
https://mp.weixin.qq.com/s/uDdmMSS0lWpUftsZsebqHA
https://mp.weixin.qq.com/s/2SNCzJI-5gsvKrLdmGCAjQ
https://mp.weixin.qq.com/s/CFSWX7he_b0Ie2roncWX1Q
https://mp.weixin.qq.com/s/6fowfuhtLLG792kWN9J3Ew

它们是换行书写的，要是批量读取下载，简直太妙

**Comment by qiye45** [comment]
可以先用监听剪切板然后下载哟，我看看下个版本能不能加上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 上午8:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 如果可以从txt文本中读取链接下载就好了 (Issue #85)




 
描述你想要的功能
 在txt文件中整理了许多公众号文章链接，如果单篇下载地复制的话，比较慢，批量读取最佳
 
比如，我的txt文件中的内容如下
 https://mp.weixin.qq.com/s/uDdmMSS0lWpUftsZsebqHA
 https://mp.weixin.qq.com/s/2SNCzJI-5gsvKrLdmGCAjQ
 https://mp.weixin.qq.com/s/CFSWX7he_b0Ie2roncWX1Q
 https://mp.weixin.qq.com/s/6fowfuhtLLG792kWN9J3Ew
 
它们是换行书写的，要是批量读取下载，简直太妙

**Comment by qiye45** [comment]
合并到 https://github.com/qiye45/wechatDownload/issues/60 啦
