### ISSUE TITLE
在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此

### ISSUE THREAD

**Issue by SimmyCHN** [qiye45/wechatDownload#87]
在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此

![1715147704235](https://github.com/qiye45/wechatDownload/assets/123547016/c440569b-6df0-4490-94b4-5c7d6163a35c)

还有，想请问大佬：用微信内置浏览器打开复制的链接
指的是：不勾选这个框么？实际操作时，不管有没有勾，ID都无法获取
![Uploading 1715147807261.png…]()

**Comment by qiye45** [comment]
可能网络的问题，在哪里呢

**Comment by SimmyCHN** [comment]
找不到原因



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月08日 17:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [qiye45/wechatDownload] 在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此 (Issue #87) |

可能网络的问题，在哪里呢

**Comment by qiye45** [comment]
在海外嘛，或者加群看看咯 @changfengbox



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 下午5:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此 (Issue #87)




 找不到原因
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年05月08日 17:29 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [qiye45/wechatDownload] 在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此 (Issue #87) |
 
 可能网络的问题，在哪里呢

**Comment by SimmyCHN** [comment]
好的。谢谢，感谢一起帮我找原因。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月09日 08:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [qiye45/wechatDownload] 在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此 (Issue #87) |

在海外嘛，或者加群看看咯 @changfengbox



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 下午5:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiye45/wechatDownload] 在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此 (Issue #87)




找不到原因



---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 日期 | 2024年05月08日 17:29 |
| 收件人 | ***@***.***&gt; |
| 抄送至 | ***@***.***&gt;***@***.***&gt; |
| 主题 | Re: [qiye45/wechatDownload] 在关闭梯子的情况下也无法无法获取公众号ID。甚至重新启动电脑后不开启梯子，也是如此 (Issue #87) |

可能网络的问题，在哪里呢

**Comment by liandayoufu** [comment]
我的软件一直在转圈，无响应。

**Comment by qiye45** [comment]
> 我的软件一直在转圈，无响应。

试试新版本
