### ISSUE TITLE
始终无法获取密钥

### ISSUE THREAD

**Issue by pepsihuang** [qiye45/wechatDownload#88]
**描述该错误**
始终无法获取密钥

**截图**
![image](https://github.com/qiye45/wechatDownload/assets/6021077/69e365f4-90d7-4d44-abda-4ec3aa252c93)

**其他信息**
5.9号8点半做的尝试。使用的是最新版本2.4
测试的公众号是
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkzMDM3ODgyMw==&scene=124#wechat_redirect

win11

梯子未打开。

**Comment by qiye45** [comment]
先看看这个咯 https://github.com/qiye45/wechatDownload/issues/9



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月9日(周四) 上午8:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 始终无法获取密钥 (Issue #88)




 
描述该错误
 始终无法获取密钥
 
截图
 image.png (view on web)
 
其他信息
 5.9号8点半做的尝试。使用的是最新版本2.4
 测试的公众号是
 https://mp.weixin.qq.com/mp/profile_ext?action=home&amp;__biz=MzkzMDM3ODgyMw==&amp;scene=124#wechat_redirect
 
win11
 
梯子未打开。

**Comment by pepsihuang** [comment]
常见问题：
1.在微信打开历史消息的页面，不要用系统自带浏览器打开，用微信自带的浏览器
2.软件不要放在c盘，可能遇到没有权限的问题
3.软件目录不能有空格
4.下载时选上HTML

都确认过了。还是不行。

**Comment by qiye45** [comment]
换台电脑试一试咯
![image](https://github.com/qiye45/wechatDownload/assets/138199658/a86c86af-4268-4fe1-81c3-af650ce937dc)
![image](https://github.com/qiye45/wechatDownload/assets/138199658/473592f6-84ca-409d-83b4-b8e44d4c5cf4)

**Comment by zl1732** [comment]
你是不是没复制粘贴那个带redirect的链接，微信浏览器开一个新页面把那个链接贴进去，打开。我的https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzA5NzczMjY0NQ==&scene=124#wechat_redirect，试试
