### ISSUE TITLE
只下载了音频和jpg封面

### ISSUE THREAD

**Issue by silengogo** [qiye45/wechatDownload#89]
**描述该错误**
在win10环境，批量下载自定义日期范围内的文章，只下载了封面和音频

**截图**
![image](https://github.com/qiye45/wechatDownload/assets/60078488/fcbbf317-d982-47ab-bf37-4aee7b4b1e1c)
![image](https://github.com/qiye45/wechatDownload/assets/60078488/76e65e21-9b8f-4b6d-839c-8b1fa96e301f)

**其他信息**
主程序包未解压，直接在压缩包中双击运行

**Comment by silengogo** [comment]
只选择“导出PDF”，会出现issue种描述的问题，4种文件类型都勾选，可以下载文件

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416
