### ISSUE TITLE
单篇文章下载失败，获取公众号id后，获取密钥失败

### ISSUE THREAD

**Issue by lele99123** [qiye45/wechatDownload#9]
尝试下载单篇文章后（链接网络无误，可直接在微信自带浏览器中打开）：
![image](https://github.com/qiye45/wechatDownload/assets/28793836/c0626ed2-637d-44bc-93b5-23a3f8e09fdc)
获取公众号id后，成功获取历史记录，在微信自带浏览器打开后，获取密钥失败。
使用管理员打开仍然失败

**Comment by specialvan** [comment]
是要win11系统才行么，还是更换网络？

**Comment by qiye45** [comment]
把梯子关了试一试

**Comment by lele99123** [comment]
使用的是win10，没开vpn，肉身在国外

**Comment by qiye45** [comment]
常见解决办法：
1.在微信打开历史消息的页面，不要使用系统自带浏览器打开
2.软件不要放在c盘，可能会遇到没有权限的问题
3.软件目录不能有空格

**Comment by qiye45** [comment]
> 一切正常。已打赏

感谢🤗

**Comment by qiye45** [comment]
常见问题：
1.在微信打开历史消息的页面，不要用系统自带浏览器打开，用微信自带的浏览器
2.软件不要放在c盘，可能遇到没有权限的问题
3.软件目录不能有空格
4.**获取公众号密钥失败**：先在微信打开复制的链接，再点批量下载；**退出微信，重新打开微信后，再获取密钥**；换个微信登录，重启电脑，换台电脑
5.**操作频繁，请稍后再试**；密钥过期：下载太多触发微信风控了，等一天或者换个微信 https://github.com/qiye45/wechatDownload/issues/20
6.评论下载失败：用批量下载；或者获取到公众号秘钥，再用文章下载
7.卡在获取密钥：重启一下微信/电脑，再点击获取密钥

重新下载公众号（怎么接着上一次下载），下载500篇左右微信密钥过期了，需要重新打开软件，重新获取密钥：记一下当前页数，重新打开软件，填一下开始下载页数，可以继续下载
https://github.com/qiye45/wechatDownload/issues/344#issuecomment-2868897399 
初次使用总结，避坑指南
https://github.com/qiye45/wechatDownload/issues/125
更新微信版本方法
https://github.com/qiye45/wechatDownload/issues/174
**用Excel打开csv表格乱码**：
把CSV文件的编码方式另保存为ANSI或者UTF-8 (有BOM) ，再用Excel打开；或者用文本编辑器打开
**评论下载失败**：
用批量下载 或者 使用获取公众号ID，打开复制的链接，获取到秘钥后，再用文章下载

**Comment by lele99123** [comment]
1.
![image](https://github.com/qiye45/wechatDownload/assets/28793836/c4a05e6e-9520-48ed-b572-288965544abb)
2.3.路径为"E:\wechatDownload\微信公众号文章批量下载工具2.1.exe"
仍是相同的问题,并且在尝试下载单篇失败后经常闪退.

**Comment by qiye45** [comment]
> ![image](https://private-user-images.githubusercontent.com/28793836/296439579-c4a05e6e-9520-48ed-b572-288965544abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDIyNTAsIm5iZiI6MTcwNTI0MTk1MCwicGF0aCI6Ii8yODc5MzgzNi8yOTY0Mzk1NzktYzRhMDVlNmUtOTUyMC00OGVkLWI1NzItMjg4OTY1NTQ0YWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NmM1MGY4ZDYyNDU1MDVmMzQ0NWY1MWUxMGUyYTkyMTNjODUwZjI3NWZiYmExZjM2ZmYwOWVjODYyNmRjNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TwbcGD9OjUX3fVWeqdXCHOuzMjsV2pN1TLnVJcqGRgw) 2.3.路径为"E:\wechatDownload\微信公众号文章批量下载工具2.1.exe" 仍是相同的问题,并且在尝试下载单篇失败后经常闪退.

要不加群看看吧，https://t.me/changfengbox

**Comment by qiye45** [comment]
初次使用总结，避坑指南
https://github.com/qiye45/wechatDownload/issues/125

**Comment by Tacit-git** [comment]
![image](https://github.com/user-attachments/assets/f5042f69-f915-4978-8dd7-aade770e68e0)
好像和win版本有关，更新到了22H2之后，就一直获取失败，更新前还好好的

**Comment by tzzym** [comment]
> ![image](https://private-user-images.githubusercontent.com/40255537/348480114-f5042f69-f915-4978-8dd7-aade770e68e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjA5MDksIm5iZiI6MTcyMTg2MDYwOSwicGF0aCI6Ii80MDI1NTUzNy8zNDg0ODAxMTQtZjUwNDJmNjktZjkxNS00OTc4LThkZDctYWFkZTc3MGU2OGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIyMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMzVmMTYxNGI2MDQ3ZGQwNmZjMmMyNzkxNTkyZDc5MDNiNjBmMzQ4YjM4OTExNmI1NGExODBhYzc4ZjUxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JqRz8mFV-nqI6TBBwta53vYFBAYre6y-Rws4HwkeLQs) 好像和win版本有关，更新到了22H2之后，就一直获取失败，更新前还好好的

我用的是win11家庭版最新版，也有问题

**Comment by eckalatgithub** [comment]
上面方法可行,亲测可用.这里面有一个重要的步骤大家可能忽略了,需要把链接放在微信的文件助手,再去点击链接
我一开始也不行,这样之后就可以获取到秘钥了.
使用环境:win10企业版+WeChatSetup-3.9.10.27.exe+wechatDownload3.1

**Comment by fox-404** [comment]
> > ![image](https://private-user-images.githubusercontent.com/40255537/348480114-f5042f69-f915-4978-8dd7-aade770e68e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjA5MDksIm5iZiI6MTcyMTg2MDYwOSwicGF0aCI6Ii80MDI1NTUzNy8zNDg0ODAxMTQtZjUwNDJmNjktZjkxNS00OTc4LThkZDctYWFkZTc3MGU2OGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIyMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMzVmMTYxNGI2MDQ3ZGQwNmZjMmMyNzkxNTkyZDc5MDNiNjBmMzQ4YjM4OTExNmI1NGExODBhYzc4ZjUxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JqRz8mFV-nqI6TBBwta53vYFBAYre6y-Rws4HwkeLQs) 好像和win版本有关，更新到了22H2之后，就一直获取失败，更新前还好好的
> 
> 我用的是win11家庭版最新版，也有问题

我也是这样，Windows22之后就不行了，我的微信版本和下载版本都没变

**Comment by Midsummerlc** [comment]
> ![image](https://private-user-images.githubusercontent.com/40255537/348480114-f5042f69-f915-4978-8dd7-aade770e68e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjQxMjcsIm5iZiI6MTcyODcyMzgyNywicGF0aCI6Ii80MDI1NTUzNy8zNDg0ODAxMTQtZjUwNDJmNjktZjkxNS00OTc4LThkZDctYWFkZTc3MGU2OGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2RhOGRhYWVjZjZkYzM2MTY5YzgxZGI1MmJmMWZhY2U0NzliNzY0NWZjMzgwNzM2ODJhZDczOTEwZmQyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HikyA1nP1MtLBoy4VNYt-pZOWrABmawh9dwuEIlgGzs) 好像和win版本有关，更新到了22H2之后，就一直获取失败，更新前还好好的

确实，我看了下我的也是win10版本号22H2，也是一直获取秘钥失败

**Comment by hou0** [comment]
现在无法获取密钥了

**Comment by zrfoscar** [comment]
怎么能下载评论以及对评论的回复呢》

**Comment by qiye45** [comment]
用批量下载

**Comment by zrfoscar** [comment]
现在好像不能批量下载了

**Comment by qiye45** [comment]
试试https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416

**Comment by zrfoscar** [comment]
下载过程zho中自动暂停，然后就不开始了

**Comment by zrfoscar** [comment]
![无标题](https://github.com/user-attachments/assets/b030e452-aedc-421d-9486-9f316cb78150)

下载过程zho中自动暂停，然后就不开始了

**Comment by jzymetalgear** [comment]
请问在已经点选了pdf的情况下，为何下载的文件中没有pdf格式文件？下载的格式只有html, md, mhtml,

**Comment by leangjia** [comment]
失效了，获取不到秘钥了

**Comment by qiye45** [comment]
> 失效了，获取不到秘钥了

等3.6更新吧，支持微信4.0了

**Comment by ryanfish1** [comment]
现在无法获取密钥了吗，网页版什么时候能够增加爬取评论和回复

**Comment by leangjia** [comment]
> 现在无法获取密钥了吗，网页版什么时候能够增加爬取评论和回复

我也是无法获取密钥了。 @qiye45

**Comment by panxiying** [comment]
我也是无法获取密钥了

**Comment by ZH9zz** [comment]
无法获取密钥+1

**Comment by HeYuaNN** [comment]
1 同一个公众号的内容，下载时会在下载目录中建立两个文件夹，一个“（公众号名称）”，一个“公众号”。总共不到300篇文章，下载完成后，在“（公众号名称）”只有少量的文件，点开检查内容是完整的。在“公众号”文件夹有大量文件，打开的文件里面只有“ ：   ，   。     视频   小程序   赞   ，轻点两下取消赞   在看   ，轻点两下取消在看 ”这么一句话，是什么问题呀？

**Comment by HeYuaNN** [comment]
> 1 同一个公众号的内容，下载时会在下载目录中建立两个文件夹，一个“（公众号名称）”，一个“公众号”。总共不到300篇文章，下载完成后，在“（公众号名称）”只有少量的文件，点开检查内容是完整的。在“公众号”文件夹有大量文件，打开的文件里面只有“ ： ， 。 视频 小程序 赞 ，轻点两下取消赞 在看 ，轻点两下取消在看 ”这么一句话，是什么问题呀？

用的3.8版本，win11系统。

**Comment by qiye45** [comment]
等我更新吧

**Comment by qiye45** [comment]
> > 1 同一个公众号的内容，下载时会在下载目录中建立两个文件夹，一个“（公众号名称）”，一个“公众号”。总共不到300篇文章，下载完成后，在“（公众号名称）”只有少量的文件，点开检查内容是完整的。在“公众号”文件夹有大量文件，打开的文件里面只有“ ： ， 。 视频 小程序 赞 ，轻点两下取消赞 在看 ，轻点两下取消在看 ”这么一句话，是什么问题呀？
> 
> 用的3.8版本，win11系统。

等我更新吧

**Comment by tituo2021** [comment]
亲，win11版本3.9也是一样的
开始获取秘钥...
获取秘钥失败...请先在微信打开复制的链接

**Comment by ruanjunmin** [comment]
win11版本3.9的软件，获取秘钥成功，为什么点击下载后只下载了一个页面？
<img width="972" height="602" alt="Image" src="https://github.com/user-attachments/assets/8f4f1322-2e59-4581-9919-e2b30402a157" />

**Comment by qiye45** [comment]
试试虚拟机

**Comment by ShawnLee42** [comment]
卡在“开始获取秘钥...”上半小时都没有反应，win11，没有开梯子

**Comment by qiye45** [comment]
换台电脑或者试试虚拟机

**Comment by yixinwangcn** [comment]
<img width="1155" height="615" alt="Image" src="https://github.com/user-attachments/assets/a314344a-63df-4871-818f-680c7a454d6a" />
单篇文章下载成功，先成功获取到了公众号ID，并下载了3篇文章后，等待25秒后恢复下载了一篇卡住，后面就无法获取到ID了

**Comment by qiye45** [comment]
> <img alt="Image" width="1155" height="615" src="https://private-user-images.githubusercontent.com/226657561/493651158-a314344a-63df-4871-818f-680c7a454d6a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4MDc0MTksIm5iZiI6MTc1ODgwNzExOSwicGF0aCI6Ii8yMjY2NTc1NjEvNDkzNjUxMTU4LWEzMTQzNDRhLTYzZGYtNDg3MS04MThmLTY4MGM3YTQ1NGQ2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyNVQxMzMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWRiZWQ4YjgxMGU4YTI4OWU1NWFjMmJjNjE3ODFkMTA0NDZlNmE5NGJkOTE2NGY2OTI2NzJjZmZhNDliNDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v2yK59KJv6-DwaAKHY-vpk2bRVforlwEy6JwdRMakCY"> 单篇文章下载成功，先成功获取到了公众号ID，并下载了3篇文章后，等待25秒后恢复下载了一篇卡住，后面就无法获取到ID了

检测一下网络或者链接

**Comment by raidsan** [comment]
现在不行了？ 密钥也获得了，但是下载的内容都是：请在微信客户端打开链接

**Comment by sss8656** [comment]
<img width="1755" height="1246" alt="Image" src="https://github.com/user-attachments/assets/f7117d1f-2fe7-418d-8482-ed9e18130604" />合集链接无法获取id，我只能一个一个获取文章，而且合集一点合集下载那个按键就卡死

**Comment by zz2136** [comment]
输入单个链接并点击“文章下载”，显示“下载成功”，但是下载内容是错的，仅有“ ：   ，   。     视频   小程序   赞   ，轻点两下取消赞   在看   ，轻点两下取消在看 ”这句话。
更换电脑下载，或者等1天后再下载还是下载失败，网页版下载结果为“未知错误”。

**Comment by zhengruncun-rgb** [comment]
下载五六篇后暂停一直不动是什么问题？4.5的版本
