### ISSUE TITLE
评论和回复选项无法选中

### ISSUE THREAD

**Issue by LievenLin** [qiye45/wechatDownload#90]
描述该错误
下载评论回复选项无法选中

截图
最后如果文章里有回复被折叠是无法下载下来
![2024-05-12_0-57-48](https://github.com/qiye45/wechatDownload/assets/20855817/8fa5f2cd-2f51-4457-943c-608403821a53)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
https://github.com/qiye45/wechatDownload/issues/52



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月12日(周日) 凌晨0:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/wechatDownload] 评论和回复选项无法选中 (Issue #90)




 
描述该错误
 下载评论回复选项无法选中
 
截图
 最后如果文章里有回复被折叠是无法下载下来
 2024-05-12_0-57-48.jpg (view on web)
 
其他信息
 在这里添加关于该问题的任何其他背景。

**Comment by LievenLin** [comment]
邮件已查收。
