### ISSUE TITLE
下载多篇公众号文章后评论无法下载

### ISSUE THREAD

**Issue by hydrogen1222** [qiye45/wechatDownload#91]
描述该错误
对该错误的简明扼要的描述。我尝试下载科研共进社的全部文章并勾选下载评论，前面部分的评论能正常下载但是后面部分无法下载评论

截图
添加截图以帮助解释你的问题。

![image](https://github.com/qiye45/wechatDownload/assets/126487811/56a551e7-763a-4a36-be6b-f7a6a1a09b9a)

其他信息
在这里添加关于该问题的任何其他背景。

**Comment by qiye45** [comment]
奇怪了，我看看

**Comment by hydrogen1222** [comment]
> 奇怪了，我看看

感谢大佬，并且我在下载前发现那个下载评论回复无法勾选上

**Comment by qiye45** [comment]
这个应该是时间太久了，token失效的原因，合并到https://github.com/qiye45/wechatDownload/issues/72 啦，下次应该会加上跳过下载的
