### ISSUE TITLE
如果是纯图片的文章，好像就扒取不了，图文格式的下载

### ISSUE THREAD

**Issue by luchenwei9266** [qiye45/wechatDownload#93]
描述该错误
比如有些公众号它的公众号文章就是放了两张图片的，这样的好像就采集不了。

截图
比如这个公众号的文章：
https://mp.weixin.qq.com/s/77YOb8SMP83I2lj6f0Uvpg

**Comment by qiye45** [comment]
这种是图文格式，我看看能不能加上吧

**Comment by qiye45** [comment]
2.6 支持图文格式啦
![image](https://github.com/qiye45/wechatDownload/assets/138199658/f591e39a-1cb6-429b-ac6b-f965ac0fb435)
