### ISSUE TITLE
获取秘钥失败....

### ISSUE THREAD

**Issue by LiuDuFenLi** [qiye45/wechatDownload#96]
换了几个公众号提示 获取秘钥失败....
![3333](https://github.com/qiye45/wechatDownload/assets/18546562/af6ad98d-4747-41b8-8561-0874131c2a20)

**Comment by qiye45** [comment]
试试这个 https://github.com/qiye45/wechatDownload/issues/9#issuecomment-1889249416

**Comment by LiuDuFenLi** [comment]
试过了，不行的。
软件目录是，D:\wechatDownload2.4

**Comment by qiye45** [comment]
换台电脑试试咯 Σ( ￣□￣||)<
