### ISSUE TITLE
无法连接到服务器如何解决？

### ISSUE THREAD

**Issue by administrator-WD** [qiye45/wechatDownload#97]
系统为win11
![image](https://github.com/qiye45/wechatDownload/assets/73874054/f23d9664-b7ff-448b-ac69-d854d50bba87)

**Comment by qiye45** [comment]
网络问题，换个网络试试

**Comment by qiye45** [comment]
在哪里呢

**Comment by administrator-WD** [comment]
> 在哪里呢

在公司回家试试，有没有微信交流群。

**Comment by qiye45** [comment]
聊天群：https://t.me/changfengbox
